<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="author" content="Diego Nieto Lugilde" />

<meta name="date" content="2017-06-29" />

<title>EPDr vignette</title>



<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>



<link href="data:text/css;charset=utf-8,body%20%7B%0Abackground%2Dcolor%3A%20%23fff%3B%0Amargin%3A%201em%20auto%3B%0Amax%2Dwidth%3A%20700px%3B%0Aoverflow%3A%20visible%3B%0Apadding%2Dleft%3A%202em%3B%0Apadding%2Dright%3A%202em%3B%0Afont%2Dfamily%3A%20%22Open%20Sans%22%2C%20%22Helvetica%20Neue%22%2C%20Helvetica%2C%20Arial%2C%20sans%2Dserif%3B%0Afont%2Dsize%3A%2014px%3B%0Aline%2Dheight%3A%201%2E35%3B%0A%7D%0A%23header%20%7B%0Atext%2Dalign%3A%20center%3B%0A%7D%0A%23TOC%20%7B%0Aclear%3A%20both%3B%0Amargin%3A%200%200%2010px%2010px%3B%0Apadding%3A%204px%3B%0Awidth%3A%20400px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Aborder%2Dradius%3A%205px%3B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Afont%2Dsize%3A%2013px%3B%0Aline%2Dheight%3A%201%2E3%3B%0A%7D%0A%23TOC%20%2Etoctitle%20%7B%0Afont%2Dweight%3A%20bold%3B%0Afont%2Dsize%3A%2015px%3B%0Amargin%2Dleft%3A%205px%3B%0A%7D%0A%23TOC%20ul%20%7B%0Apadding%2Dleft%3A%2040px%3B%0Amargin%2Dleft%3A%20%2D1%2E5em%3B%0Amargin%2Dtop%3A%205px%3B%0Amargin%2Dbottom%3A%205px%3B%0A%7D%0A%23TOC%20ul%20ul%20%7B%0Amargin%2Dleft%3A%20%2D2em%3B%0A%7D%0A%23TOC%20li%20%7B%0Aline%2Dheight%3A%2016px%3B%0A%7D%0Atable%20%7B%0Amargin%3A%201em%20auto%3B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dcolor%3A%20%23DDDDDD%3B%0Aborder%2Dstyle%3A%20outset%3B%0Aborder%2Dcollapse%3A%20collapse%3B%0A%7D%0Atable%20th%20%7B%0Aborder%2Dwidth%3A%202px%3B%0Apadding%3A%205px%3B%0Aborder%2Dstyle%3A%20inset%3B%0A%7D%0Atable%20td%20%7B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dstyle%3A%20inset%3B%0Aline%2Dheight%3A%2018px%3B%0Apadding%3A%205px%205px%3B%0A%7D%0Atable%2C%20table%20th%2C%20table%20td%20%7B%0Aborder%2Dleft%2Dstyle%3A%20none%3B%0Aborder%2Dright%2Dstyle%3A%20none%3B%0A%7D%0Atable%20thead%2C%20table%20tr%2Eeven%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Ap%20%7B%0Amargin%3A%200%2E5em%200%3B%0A%7D%0Ablockquote%20%7B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Apadding%3A%200%2E25em%200%2E75em%3B%0A%7D%0Ahr%20%7B%0Aborder%2Dstyle%3A%20solid%3B%0Aborder%3A%20none%3B%0Aborder%2Dtop%3A%201px%20solid%20%23777%3B%0Amargin%3A%2028px%200%3B%0A%7D%0Adl%20%7B%0Amargin%2Dleft%3A%200%3B%0A%7D%0Adl%20dd%20%7B%0Amargin%2Dbottom%3A%2013px%3B%0Amargin%2Dleft%3A%2013px%3B%0A%7D%0Adl%20dt%20%7B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0Aul%20%7B%0Amargin%2Dtop%3A%200%3B%0A%7D%0Aul%20li%20%7B%0Alist%2Dstyle%3A%20circle%20outside%3B%0A%7D%0Aul%20ul%20%7B%0Amargin%2Dbottom%3A%200%3B%0A%7D%0Apre%2C%20code%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0Aborder%2Dradius%3A%203px%3B%0Acolor%3A%20%23333%3B%0Awhite%2Dspace%3A%20pre%2Dwrap%3B%20%0A%7D%0Apre%20%7B%0Aborder%2Dradius%3A%203px%3B%0Amargin%3A%205px%200px%2010px%200px%3B%0Apadding%3A%2010px%3B%0A%7D%0Apre%3Anot%28%5Bclass%5D%29%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Acode%20%7B%0Afont%2Dfamily%3A%20Consolas%2C%20Monaco%2C%20%27Courier%20New%27%2C%20monospace%3B%0Afont%2Dsize%3A%2085%25%3B%0A%7D%0Ap%20%3E%20code%2C%20li%20%3E%20code%20%7B%0Apadding%3A%202px%200px%3B%0A%7D%0Adiv%2Efigure%20%7B%0Atext%2Dalign%3A%20center%3B%0A%7D%0Aimg%20%7B%0Abackground%2Dcolor%3A%20%23FFFFFF%3B%0Apadding%3A%202px%3B%0Aborder%3A%201px%20solid%20%23DDDDDD%3B%0Aborder%2Dradius%3A%203px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Amargin%3A%200%205px%3B%0A%7D%0Ah1%20%7B%0Amargin%2Dtop%3A%200%3B%0Afont%2Dsize%3A%2035px%3B%0Aline%2Dheight%3A%2040px%3B%0A%7D%0Ah2%20%7B%0Aborder%2Dbottom%3A%204px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Apadding%2Dbottom%3A%202px%3B%0Afont%2Dsize%3A%20145%25%3B%0A%7D%0Ah3%20%7B%0Aborder%2Dbottom%3A%202px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Afont%2Dsize%3A%20120%25%3B%0A%7D%0Ah4%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23f7f7f7%3B%0Amargin%2Dleft%3A%208px%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Ah5%2C%20h6%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23ccc%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Aa%20%7B%0Acolor%3A%20%230033dd%3B%0Atext%2Ddecoration%3A%20none%3B%0A%7D%0Aa%3Ahover%20%7B%0Acolor%3A%20%236666ff%3B%20%7D%0Aa%3Avisited%20%7B%0Acolor%3A%20%23800080%3B%20%7D%0Aa%3Avisited%3Ahover%20%7B%0Acolor%3A%20%23BB00BB%3B%20%7D%0Aa%5Bhref%5E%3D%22http%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0Aa%5Bhref%5E%3D%22https%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0A%0Acode%20%3E%20span%2Ekw%20%7B%20color%3A%20%23555%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Edt%20%7B%20color%3A%20%23902000%3B%20%7D%20%0Acode%20%3E%20span%2Edv%20%7B%20color%3A%20%2340a070%3B%20%7D%20%0Acode%20%3E%20span%2Ebn%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Efl%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Ech%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Est%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Eco%20%7B%20color%3A%20%23888888%3B%20font%2Dstyle%3A%20italic%3B%20%7D%20%0Acode%20%3E%20span%2Eot%20%7B%20color%3A%20%23007020%3B%20%7D%20%0Acode%20%3E%20span%2Eal%20%7B%20color%3A%20%23ff0000%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Efu%20%7B%20color%3A%20%23900%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%20code%20%3E%20span%2Eer%20%7B%20color%3A%20%23a61717%3B%20background%2Dcolor%3A%20%23e3d2d2%3B%20%7D%20%0A" rel="stylesheet" type="text/css" />

</head>

<body>




<h1 class="title toc-ignore">EPDr vignette</h1>
<h4 class="author"><em>Diego Nieto Lugilde</em></h4>
<h4 class="date"><em>2017-06-29</em></h4>


<div id="TOC">
<ul>
<li><a href="#installing-the-epdr-package"><span class="toc-section-number">1</span> Installing the EPDr package</a></li>
<li><a href="#setting-up-the-epd-database"><span class="toc-section-number">2</span> Setting up the EPD database</a></li>
<li><a href="#loading-the-epdr-package"><span class="toc-section-number">3</span> Loading the EPDr package</a></li>
<li><a href="#connecting-to-the-epd-database"><span class="toc-section-number">4</span> Connecting to the EPD database</a></li>
<li><a href="#querying-data-from-the-database"><span class="toc-section-number">5</span> Querying data from the database</a><ul>
<li><a href="#listing-fields-from-the-epd-list-functions"><span class="toc-section-number">5.1</span> Listing fields from the EPD (<code>list</code> functions)</a></li>
<li><a href="#retrieving-information-for-particular-entities-get-functions"><span class="toc-section-number">5.2</span> Retrieving information for particular entities (<code>get</code> functions)</a></li>
</ul></li>
<li><a href="#working-with-data-from-the-epd"><span class="toc-section-number">6</span> Working with data from the EPD</a><ul>
<li><a href="#exporting-data-for-clam-or-bacon"><span class="toc-section-number">6.1</span> Exporting data for CLAM or BACON</a></li>
<li><a href="#standardizing-data"><span class="toc-section-number">6.2</span> Standardizing data</a><ul>
<li><a href="#reformat-data-into-matrices-epd.entity.df"><span class="toc-section-number">6.2.1</span> Reformat data into matrices (<code>epd.entity.df</code>)</a></li>
<li><a href="#navigating-taxonomy-in-the-epd"><span class="toc-section-number">6.2.2</span> Navigating taxonomy in the EPD</a></li>
<li><a href="#filtering-taxa"><span class="toc-section-number">6.2.3</span> Filtering taxa</a></li>
<li><a href="#calculating-percentages"><span class="toc-section-number">6.2.4</span> Calculating percentages</a></li>
<li><a href="#using-updated-ages-from-giesecke-et-al.--giesecke_2013"><span class="toc-section-number">6.2.5</span> Using updated ages from Giesecke <em>et al.</em> <span class="citation">(2013)</span></a></li>
<li><a href="#interpolating-counts-data-to-specific-time-periods"><span class="toc-section-number">6.2.6</span> Interpolating counts data to specific time periods</a></li>
<li><a href="#average-counts-data-to-specific-time-ranges"><span class="toc-section-number">6.2.7</span> Average counts data to specific time ranges</a></li>
<li><a href="#calculating-data-quality-using-blois_2011"><span class="toc-section-number">6.2.8</span> Calculating data quality using <span class="citation">(Blois et al. 2011)</span></a></li>
</ul></li>
</ul></li>
<li><a href="#references">References</a></li>
</ul>
</div>

<p>In this vignette we will illustrate the use of EPDr package, from installing the package to retrieving data from a local server of the European Pollen Database (EPD) and how to use those data to perform some basic analysis and produce most common plots in paleopalynology, like palynograms or maps.</p>
<div id="installing-the-epdr-package" class="section level1">
<h1><span class="header-section-number">1</span> Installing the EPDr package</h1>
<p>User can choose to install the latest development version from github or the latest released version from CRAN.</p>
<p>The development version from github can be installed using the <code>install_github</code> function from the <code>devtools</code>package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(devtools)
<span class="kw">install_github</span>(<span class="st">&quot;dinilu/EPDr&quot;</span>, <span class="dt">force =</span> T)</code></pre></div>
<p>Alternatively, the last released version can be installed from CRAN using the usual <code>install.package</code> function</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">install.packages</span>(<span class="st">&quot;EPDr&quot;</span>)</code></pre></div>
</div>
<div id="setting-up-the-epd-database" class="section level1">
<h1><span class="header-section-number">2</span> Setting up the EPD database</h1>
<p>Before moving on with this vignette, it is important that the user have access to a running PostgreSQL server with the EPD database. This is where the data are going to be pulled out. Detailed, and step by step, instructions to do so in a local-host are in a specific vignette along with the EPDr package. Check the vignette in the following code if you have not yet.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">vignette</span>(<span class="st">&quot;EPD-PostgreSQL&quot;</span>, <span class="dt">package =</span> <span class="st">&quot;EPDr&quot;</span>)</code></pre></div>
</div>
<div id="loading-the-epdr-package" class="section level1">
<h1><span class="header-section-number">3</span> Loading the EPDr package</h1>
<p>As any other R-package, <code>ÈPDr</code> is loaded in the working environment with the <code>library</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(EPDr)</code></pre></div>
</div>
<div id="connecting-to-the-epd-database" class="section level1">
<h1><span class="header-section-number">4</span> Connecting to the EPD database</h1>
<p>The <code>EPDr</code> package uses the <code>RPostgreSQL</code> package to establish a connection between the R session and the EPD database in the PostgreSQL server. Although this can be done to a online server, we assume most users do not have the expertise to setup an online server and most are thus running the server and the R session in the same computer (localhost configuration).</p>
<p>To establish the connection we use the <code>connect_to_epd</code> function, which requires the following arguments: <em><code>database</code>: database name. No default database name is specified in the function. </em><code>user</code>: user name. Name of the user with privileges to access the database. No default user name is specified in the function. <em><code>password</code>: user’s password. Password of the user to access the database. </em><code>host</code>: address to the server. “localhost” is the default value indicating that the server is running in the local computer.</p>
<p>If the function is called with no arguments <code>connect_to_epd()</code>, the function assume the server is running in the local computer (“locahost”), and interactively ask for the necessary arguments to connect with the database: <code>database</code>, <code>user</code>, and <code>password</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.connection &lt;-<span class="st"> </span><span class="kw">connect_to_epd</span>(<span class="dt">database =</span> <span class="st">&quot;epd&quot;</span>, <span class="dt">user =</span> <span class="st">&quot;epdr&quot;</span>, <span class="dt">password =</span> <span class="st">&quot;epdrpw&quot;</span>)</code></pre></div>
<p>In case you have access to a remote EPD server, you only have to provide the online address to the server using the argument <code>host</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.connection &lt;-<span class="st"> </span><span class="kw">connect_to_epd</span>(<span class="dt">database =</span> <span class="st">&quot;epd&quot;</span>, <span class="dt">user =</span> <span class="st">&quot;epdr&quot;</span>, <span class="dt">password =</span> <span class="st">&quot;epdrpw&quot;</span>, <span class="dt">host =</span> <span class="st">&quot;http://remote.epd.server&quot;</span>)</code></pre></div>
<p>Now, we are ready to check the connection with some of the functions in the <code>RPostgreSQL</code> and/or <code>DBI</code> packages. For instance, we can use the <code>dbListTables</code> function to get a list of all the tables in the database. The function should return a list of 45 tables.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(DBI)
<span class="kw">dbListTables</span>(epd.connection)</code></pre></div>
<pre><code>##  [1] &quot;descr&quot;    &quot;chron&quot;    &quot;entity&quot;   &quot;authors&quot;  &quot;groups&quot;   &quot;coredriv&quot;
##  [7] &quot;geochron&quot; &quot;esr&quot;      &quot;p_counts&quot; &quot;c14&quot;      &quot;ft&quot;       &quot;p_entity&quot;
## [13] &quot;kar&quot;      &quot;event&quot;    &quot;p_group&quot;  &quot;infotype&quot; &quot;litholgy&quot; &quot;loi&quot;     
## [19] &quot;alsegs&quot;   &quot;igcptype&quot; &quot;p_sample&quot; &quot;agebound&quot; &quot;p_anldpt&quot; &quot;p_agedpt&quot;
## [25] &quot;p_vtrans&quot; &quot;poldiv1&quot;  &quot;siteloc&quot;  &quot;section&quot;  &quot;si32&quot;     &quot;publ&quot;    
## [31] &quot;p_vars&quot;   &quot;sitedesc&quot; &quot;useries&quot;  &quot;synevent&quot; &quot;siteinfo&quot; &quot;syntype&quot; 
## [37] &quot;poldiv2&quot;  &quot;aar&quot;      &quot;poldiv3&quot;  &quot;rational&quot; &quot;agebasis&quot; &quot;publent&quot; 
## [43] &quot;workers&quot;  &quot;tl&quot;       &quot;pb210&quot;</code></pre>
</div>
<div id="querying-data-from-the-database" class="section level1">
<h1><span class="header-section-number">5</span> Querying data from the database</h1>
<p>The EPDr package provide several ways to retrieve data from the database: Listing information from different fields in the database with <code>list</code> functions, or extracting specific data for a particular entity (pollen core, polster sample, etc.) with <code>get</code> functions.</p>
<div id="listing-fields-from-the-epd-list-functions" class="section level2">
<h2><span class="header-section-number">5.1</span> Listing fields from the EPD (<code>list</code> functions)</h2>
<p>For users unfamiliar with the database it might be useful to list elements in the database, for instance to know which countries are represented or which publications are associated with the entities in the database. To do so, the package provides a series of <code>list</code> functions that return specific tables from the database where important information can be looked at.</p>
<p>Some of these functions (<code>list_countries</code> and <code>list_taxagroups</code>) only accept one argument (<code>connection</code>), which must be a valid connection to the EPD database.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">list_countries</span>(epd.connection)</code></pre></div>
<pre><code>##    poldiv1                                   name
## 1      ADS                           Adriatic Sea
## 2      AFG                            Afghanistan
## 3      ALA                         Ãland Islands
## 4      ALB                                Albania
## 5      AND                                Andorra
## 6      ARE                   United Arab Emirates
## 7      ARM                                Armenia
##  [ reached getOption(&quot;max.print&quot;) -- omitted 83 rows ]</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">list_taxagroups</span>(epd.connection)</code></pre></div>
<pre><code>##    groupid groupcode                             groupname
## 1     ACRI         ?                            Acritarchs
## 2     ALGA         L                                 Algae
## 3     AQPT         K                  Aquatic Pteridophyta
## 4     AQUA         Q                              Aquatics
## 5     BRYO         M                            Bryophytes
##  [ reached getOption(&quot;max.print&quot;) -- omitted 24 rows ]</code></pre>
<p>However, other <code>list</code> functions accept several arguments to further filter the result of the query. For instance, <code>list_regions</code> accepts an extra argument (<code>country</code>) to limit the query to particular countries.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">list_regions</span>(epd.connection)</code></pre></div>
<pre><code>##      poldiv2 poldiv1                             regionname
## 1         00     ADS                                   &lt;NA&gt;
## 2         00     AFG                                   &lt;NA&gt;
## 3         00     ALA                                   &lt;NA&gt;
## 4         00     ALB                                   &lt;NA&gt;
## 5         01     ALB                        Qarku i Beratit
## 6         02     ALB                         Qarku i Dibres
## 7         03     ALB                       Qarku i Durresit
## 8         04     ALB                      Qarku i Elbasanit
## 9         05     ALB                         Qarku i Fierit
## 10        06     ALB                   Qarku i Gjirokastres
##                                 countryname
## 1                              Adriatic Sea
## 2                               Afghanistan
## 3                            Ãland Islands
## 4                                   Albania
## 5                                   Albania
## 6                                   Albania
## 7                                   Albania
## 8                                   Albania
## 9                                   Albania
## 10                                  Albania
##  [ reached getOption(&quot;max.print&quot;) -- omitted 2039 rows ]</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">list_regions</span>(epd.connection, <span class="dt">country =</span> <span class="st">&quot;Spain&quot;</span>)</code></pre></div>
<pre><code>##    poldiv2 poldiv1            regionname countryname
## 1       00     ESP                  &lt;NA&gt;       Spain
## 2       01     ESP             Andalucia       Spain
## 3       02     ESP                Aragon       Spain
## 4       03     ESP              Asturias       Spain
## 5       04     ESP              Baleares       Spain
## 6       05     ESP              Canarias       Spain
## 7       06     ESP             Cantabria       Spain
## 8       07     ESP    Castilla-La Mancha       Spain
## 9       08     ESP       Castilla y Leon       Spain
## 10      09     ESP              Cataluna       Spain
##  [ reached getOption(&quot;max.print&quot;) -- omitted 10 rows ]</code></pre>
<p>Each function has their own relevant parameters. For instance, <code>list_taxa</code> accepts the argument <code>group_id</code>, which refers to the taxa groups from <code>list_taxagroups</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">list_taxa</span>(epd.connection)</code></pre></div>
<pre><code>##      var_                                            varname   varcode
## 1       1                                              Abies       Abi
## 2    1987                                         Abies alba     Abi.a
## 3    2644                                     Abies marocana     Abi.m
## 4    2493                                 Abies nordmanniana     Abi.n
##      mhvar_ groupid
## 1         1    TRSH
## 2         1    TRSH
## 3         1    TRSH
## 4         1    TRSH
##  [ reached getOption(&quot;max.print&quot;) -- omitted 5474 rows ]</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">list_taxa</span>(epd.connection, <span class="dt">group_id =</span> <span class="st">&quot;HERB&quot;</span>)</code></pre></div>
<pre><code>##      var_                                            varname   varcode
## 1    1869                                           Abutilon       Abu
## 2    2721                                        Acanthaceae  Acanteae
## 3    1852                                       Acantholimon       Alm
## 4    1763                                           Acanthus       Atu
##      mhvar_ groupid
## 1       472    HERB
## 2      1763    HERB
## 3       595    HERB
## 4      1763    HERB
##  [ reached getOption(&quot;max.print&quot;) -- omitted 2796 rows ]</code></pre>
<p>Other <code>list</code> functions accept more arguments. Sample sites, for instance, can be listed specifying the <code>country</code> and <code>region</code> of interest, but also a set of four geographical coordinates (longitude and latitude) encompassing the area of interest (xmin, xmax, ymin, ymax).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">list_sites</span>(epd.connection)</code></pre></div>
<pre><code>##      site_                               sitename        sitecode    latdd
## 1        1                                 Adange  GEO-01000-ADAN 43.30556
## 2        2                         AgerÃ¶ds Mosse  SWE-13000-AGER 55.83333
##            londd elevation areaofsite
## 1      41.333333      1750 2.5000e-01
## 2      13.416667        58 1.5000e+02
##                                                          sitedescript
## 1                                             Meander of Adange river
## 2                                               Forested Sphagnum bog
##                                      physiography
## 1               Fluvial terrace above flood-plain
## 2                                            till
##                                                                       surroundveg
## 1                                            Subalpine tall herbaceous vegetation
## 2                                                         pasture and arable land
##                                   vegformation
## 1                                         &lt;NA&gt;
## 2                                         &lt;NA&gt;
##  [ reached getOption(&quot;max.print&quot;) -- omitted 1874 rows ]</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">list_sites</span>(epd.connection, <span class="dt">country =</span> <span class="st">&quot;Spain&quot;</span>, <span class="dt">region =</span> <span class="st">&quot;Andalucia&quot;</span>)</code></pre></div>
<pre><code>##   site_        sitename       sitecode    latdd     londd elevation
## 1    65           Antas ESP-01000-ANTA 37.20833 -1.823611         0
## 2   306   Laguna Grande ESP-01000-LAGU 37.10833 -4.316667       800
##   areaofsite                sitedescript
## 1         NA                   Sea shore
## 2          4             Spring-fed lake
##                                 physiography
## 1                                       flat
## 2                         in limestone hills
##                               surroundveg vegformation
## 1                                    &lt;NA&gt;         &lt;NA&gt;
## 2                                    &lt;NA&gt;         &lt;NA&gt;
##  [ reached getOption(&quot;max.print&quot;) -- omitted 7 rows ]</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">list_sites</span>(epd.connection, <span class="dt">coords =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">4</span>, <span class="dv">10</span>, <span class="dv">36</span>, <span class="dv">40</span>))</code></pre></div>
<pre><code>##    site_           sitename       sitecode    latdd     londd elevation
## 1     55           Algendar ESP-04000-ALGE 39.94056  3.958611        21
## 2     65              Antas ESP-01000-ANTA 37.20833 -1.823611         0
##    areaofsite                  sitedescript
## 1          NA South coast of Minorca Island
## 2          NA                     Sea shore
##                                physiography
## 1                             littoral core
## 2                                      flat
##                                 surroundveg                 vegformation
## 1                              Quercus ilex                         &lt;NA&gt;
## 2                                      &lt;NA&gt;                         &lt;NA&gt;
##  [ reached getOption(&quot;max.print&quot;) -- omitted 23 rows ]</code></pre>
<p>Biological counts and datation data in the EPD database are referred to entities. This account for the fact that multiple samples can be taken in the same site. For instance, several cores drilled in the the same lake, or a core and a surface sample (moss polster or pollen trap) being collected in a peat-bog.</p>
<p>Entities thus can be listed according to many different criteria: site name or site ID (<code>site</code>), geographical coordinates (<code>coords</code>), last name of the author (<code>lastname</code>), first name of the author (<code>firstname</code>), initials of the author (<code>initials</code>), publication number (<code>publ</code>), country (<code>country</code>) and region (<code>region</code>), and restriction on the use of data (<code>restrictions</code>). If multiple criteria are going to be used, the author can decide to use a logical operator to control for an additive (<code>AND</code>) or alternative (<code>OR</code>) interaction between criteria.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">list_e</span>(epd.connection)</code></pre></div>
<pre><code>##        e_ site_    sigle                            name iscore issect
## 1       1     1   ADANGE                            &lt;NA&gt;      Y      N
## 2       2     2      AGE                            &lt;NA&gt;      Y      N
##      isssamp descriptor hasanlam
## 1          Y       RFLU        N
## 2          Y       PBRA        N
##                                                          entloc
## 1                                           left coast of river
## 2                                             Center of the bog
##                                                                                                                                                                                          localveg
## 1                                                                                                                                                                                  Cyperaceae fen
## 2                                                                                                                                                                                            &lt;NA&gt;
##      coll_   sampdate depthatloc icethickcm
## 1       65 1984-08-00      210.0         NA
## 2       70 1960-00-00         NA         NA
##                                  sampdevice corediamcm c14depthadj
## 1                                     spade      10.00          NA
## 2                              piston corer       6.00          NA
##                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        notes
## 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       &lt;NA&gt;
## 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       &lt;NA&gt;
##  [ reached getOption(&quot;max.print&quot;) -- omitted 2407 rows ]</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">list_e</span>(epd.connection, <span class="dt">site =</span> <span class="st">&quot;Adange&quot;</span>)</code></pre></div>
<pre><code>##   e_ site_  sigle name iscore issect isssamp descriptor hasanlam
## 1  1     1 ADANGE &lt;NA&gt;      Y      N       Y       RFLU        N
##                entloc       localveg coll_   sampdate depthatloc
## 1 left coast of river Cyperaceae fen    65 1984-08-00        210
##   icethickcm sampdevice corediamcm c14depthadj notes site_ sitename
## 1         NA      spade         10          NA  &lt;NA&gt;     1   Adange
##         sitecode siteexists poldiv1 poldiv2 poldiv3 latdeg latmin latsec
## 1 GEO-01000-ADAN       &lt;NA&gt;     GEO      01     000     43     18     20
##   latns    latdd    latdms londeg lonmin lonsec lonew    londd     londms
## 1     N 43.30556 43.18.20N     41     20      0     E 41.33333  41.20.00E
##   elevation areaofsite
## 1      1750       0.25</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">list_e</span>(epd.connection, <span class="dt">lastname =</span> <span class="st">&quot;Tzedakis&quot;</span>)</code></pre></div>
<pre><code>##    e_ site_   sigle     name iscore issect isssamp descriptor hasanlam
## 1 294   249 IOAN249 core 249      Y      N       Y       UNKN        N
##                                     entloc localveg coll_   sampdate
## 1 Southeast of Lake Pamvotis near Kastrits     &lt;NA&gt;   415 0000-00-00
##   depthatloc icethickcm         sampdevice corediamcm c14depthadj notes
## 1         NA         NA Unspecified device         NA          NA  &lt;NA&gt;
##   worker_ workeris_ status lastname initials  firstname suffix title
## 1     415       415      A Tzedakis     P.C. P. Chronis   &lt;NA&gt;   Dr.
##   country phone  fax                emailaddr
## 1     GBR  &lt;NA&gt; &lt;NA&gt; p.c.tzedakis@leeds.ac.uk
##                                                                                                                                               address
## 1 Subdepartment of Quaternary Research\\nDepartment of Plant sciences\\nUniversity of Cambridge\\nDowning Street\\nCambridge CB2 3EA\\nUNITED KINGDOM</code></pre>
<p>When using any of these <code>list</code> functions with arguments to filter the query, we can specify multiple values. That means for instance that we can pass a vector of names as the argument <code>country</code> to the <code>list_e</code> function to get information about all the entities in all those countries.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">list_e</span>(epd.connection, <span class="dt">country =</span> <span class="kw">c</span>(<span class="st">&quot;Spain&quot;</span>, <span class="st">&quot;Portugal&quot;</span>, <span class="st">&quot;France&quot;</span>, <span class="st">&quot;Switzerland&quot;</span>, <span class="st">&quot;Austria&quot;</span>, <span class="st">&quot;Italy&quot;</span>, <span class="st">&quot;Malta&quot;</span>, <span class="st">&quot;Algeria&quot;</span>, <span class="st">&quot;Tunisia&quot;</span>, <span class="st">&quot;Morocco&quot;</span>, <span class="st">&quot;Atlantic ocean&quot;</span>, <span class="st">&quot;Mediterranean Sea&quot;</span>))</code></pre></div>
<pre><code>##        e_ site_    sigle                            name iscore issect
## 1      10    10  CARNINO                          core I      Y      N
##      isssamp descriptor hasanlam
## 1          Y       PMIR        N
##                                                          entloc
## 1                                                          &lt;NA&gt;
##                                                                                                                                                                                          localveg
## 1                                                                                                                                                                                            &lt;NA&gt;
##      coll_   sampdate depthatloc icethickcm                     sampdevice
## 1       88 0000-00-00         NA         NA             Unspecified device
##      corediamcm c14depthadj
## 1            NA          NA
##                                                                                                                                                                                                                                                             notes
## 1                                                                                                                                                                                                                                                            &lt;NA&gt;
##      site_                               sitename        sitecode
## 1       10                       Selle di Carnino  ITA-08000-SELL
##      siteexists poldiv1 poldiv2 poldiv3 latdeg latmin latsec latns
## 1          &lt;NA&gt;     ITA      08     000     44      9      0     N
##         latdd    latdms londeg lonmin lonsec lonew      londd     londms
## 1    44.15000 44.09.00N      7     41     40     E   7.694444   7.41.40E
##      elevation areaofsite poldiv1              name
## 1         1905       5.00     ITA             Italy
##  [ reached getOption(&quot;max.print&quot;) -- omitted 1000 rows ]</code></pre>
<p>Finally, the <code>list_publ</code> function allow to search the publications we need to cite if are going to use any of the data-sets in the database. This function thus allow to search publications for several criteria, including entity number (<code>e_</code>).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">list_publ</span>(epd.connection)</code></pre></div>
<pre><code>##      publ_   e_ acc_ yearofpubl
## 1        1   40   NA       1994
## 2        1   41   NA       1994
##                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         citation
## 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Kremenetski, C.V., P.E. Tarasov, and A.E. Cherkinsky. 1994. Istoriva ostrovnykh borov Kazakhstana v golotsene [Holocene history of the Kazakhstan &quot;island&quot; pine forests]. Botanicheski Zhurial [Botanical Journal], 79(3):13-29.
## 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Kremenetski, C.V., P.E. Tarasov, and A.E. Cherkinsky. 1994. Istoriva ostrovnykh borov Kazakhstana v golotsene [Holocene history of the Kazakhstan &quot;island&quot; pine forests]. Botanicheski Zhurial [Botanical Journal], 79(3):13-29.
##  [ reached getOption(&quot;max.print&quot;) -- omitted 3166 rows ]</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">list_publ</span>(epd.connection, <span class="dt">e_ =</span> <span class="dv">1</span>)</code></pre></div>
<pre><code>##   publ_ e_ acc_ yearofpubl
## 1    16  1   NA       1989
##                                                                                                                                         citation
## 1 Kvavadze, E.V., and L.P. Rukhadze. 1989. Vegetation and climate of the Holocene of Abkhazia. Metsniereba, Tbilisi, Georgia, 138p (in Russian).</code></pre>
</div>
<div id="retrieving-information-for-particular-entities-get-functions" class="section level2">
<h2><span class="header-section-number">5.2</span> Retrieving information for particular entities (<code>get</code> functions)</h2>
<p>So far, we have been able to look for metadata information (details on country, region, or site) to which entities of the database belong to, but most times we are interested in extracting biological information, along with chronological information that allows us to dating the corresponding biological information, for those particular entities. The <code>EPDr</code> package provide a set of <code>get</code> functions specially designed for this task.</p>
<p>All these <code>get</code> functions have been designed to query data for a particular entity in the database. Hence, most of them (but <code>get_taxonomy_epd</code> and some others) accept two arguments: entity ID (<code>e_</code>) and a valid connection to the EPD database (<code>connection</code>). Note that entities has to be referred by their ID number and not by their sigle name. If you know the sigle of a particular entity, you need to use the <code>list_e</code> function and look for the <code>e_</code> number for that particular <code>sigle</code>.</p>
<p>These functions are divided in two groups. The first one is comprised by a set of <code>get</code> functions that returns single data frames that resemble the tables in the EPD in which information is restricted for the queried entity (<code>e_</code>). All these functions are called <code>.get_</code> functions followed by a reference to the table they query. Because the standar user usually won’t use these functions we do not provide here any example. These functions works also behind the hook in other <code>get_</code> functions.</p>
<p>The second group of functions, named as <code>get_</code> functions followed by a small descriptor, retrieve information from different tables (using <code>.get_</code> functions) for related data in an entity. Although most user won’t need these functions, it is good for them to get familiar with the data structure they return, because they are the same in other more common functions and objects they return. These functions are: <code>get_ent</code>, <code>get_site</code>, <code>get_geochron</code>, <code>get_chron</code>, or <code>get_samples</code>. Because these wrapping functions query information from different tables, they return especial S4 class objects that have been designed for the package. Different tables are stored in different slots of the objects.</p>
<p>For instance, <code>get_ent</code> retrieves information that describe the entity that is queried. It returns a specific object, that has several data frames each one corresponding with one table in the EPD related with the description of the entity.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ent.<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">get_ent</span>(<span class="dv">1</span>, epd.connection)
<span class="kw">class</span>(ent.<span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] &quot;entity&quot;
## attr(,&quot;package&quot;)
## [1] &quot;EPDr&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">slotNames</span>(ent.<span class="dv">1</span>)</code></pre></div>
<pre><code>##  [1] &quot;entity&quot;    &quot;pentity&quot;   &quot;contact&quot;   &quot;coredrive&quot; &quot;descr&quot;    
##  [6] &quot;lithology&quot; &quot;loi&quot;       &quot;section&quot;   &quot;publent&quot;   &quot;publ&quot;</code></pre>
<p>Similarly, <code>get_site</code> returns a new object that has several tables describing the site where the entity was sampled.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">site.<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">get_site</span>(<span class="dv">1</span>, epd.connection)
<span class="kw">class</span>(site.<span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] &quot;site&quot;
## attr(,&quot;package&quot;)
## [1] &quot;EPDr&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">slotNames</span>(site.<span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] &quot;siteloc&quot;   &quot;sitedesc&quot;  &quot;siteinfo&quot;  &quot;country&quot;   &quot;region&quot;    &quot;region3rd&quot;
## [7] &quot;igcptype&quot;  &quot;infotype&quot;  &quot;publ&quot;</code></pre>
<p>The <code>get_geochron</code> function returns all geochronological data for a particular entity. This is a description of the geochronological samples (sample id, depth, thickness, etc.) as well as the details of the analitical results from different techniques (C<sup>14</sup>, aminoacid racemization, etc.)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">geochron.<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">get_geochron</span>(<span class="dv">1</span>, epd.connection)
<span class="kw">class</span>(geochron.<span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] &quot;geochron&quot;
## attr(,&quot;package&quot;)
## [1] &quot;EPDr&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">slotNames</span>(geochron.<span class="dv">1</span>)</code></pre></div>
<pre><code>##  [1] &quot;geochron&quot; &quot;aar&quot;      &quot;c14&quot;      &quot;esr&quot;      &quot;ft&quot;       &quot;kar&quot;     
##  [7] &quot;pb210&quot;    &quot;si32&quot;     &quot;tl&quot;       &quot;useries&quot;  &quot;publ&quot;</code></pre>
<p>However, <code>get_chron</code> retrieves all data relative to the chronologies stored in the EPD for a particular entity.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">chron.<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">get_chron</span>(<span class="dv">1</span>, epd.connection)
<span class="kw">class</span>(chron.<span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] &quot;chron&quot;
## attr(,&quot;package&quot;)
## [1] &quot;EPDr&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">slotNames</span>(chron.<span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] &quot;chron&quot;    &quot;agebound&quot; &quot;agebasis&quot; &quot;rational&quot; &quot;alsegs&quot;   &quot;panldpt&quot; 
## [7] &quot;synevent&quot; &quot;event&quot;    &quot;publ&quot;</code></pre>
<p>Similarly, <code>get_samples</code> retrieves information from all tables about biological samples for the entity.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">samples.<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">get_samples</span>(<span class="dv">1</span>, epd.connection)
<span class="kw">class</span>(samples.<span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] &quot;samples&quot;
## attr(,&quot;package&quot;)
## [1] &quot;EPDr&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">slotNames</span>(samples.<span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] &quot;psamples&quot; &quot;analysts&quot; &quot;pagedpt&quot;  &quot;pcounts&quot;  &quot;pvars&quot;    &quot;syntype&quot; 
## [7] &quot;pvtrans&quot;  &quot;pgroup&quot;   &quot;groups&quot;</code></pre>
<p>Above these functions, there is a special one (<code>get_entity</code>), which in turns retrieve all possible information from the different tables and <code>get_</code> functions for an entity. Most user, will only need <code>get_entity</code> in their working flow, because the <code>epd.entity</code> objects it returns include all the objects from the previous <code>get_</code> functions.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">get_entity</span>(<span class="dv">1</span>, epd.connection)
<span class="kw">class</span>(epd.<span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] &quot;epd.entity&quot;
## attr(,&quot;package&quot;)
## [1] &quot;EPDr&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">slotNames</span>(epd.<span class="dv">1</span>)</code></pre></div>
<pre><code>##  [1] &quot;e_&quot;            &quot;postbombzone&quot;  &quot;numberofchron&quot; &quot;isingiesecke&quot; 
##  [5] &quot;defaultchron&quot;  &quot;entity&quot;        &quot;site&quot;          &quot;geochron&quot;     
##  [9] &quot;chron&quot;         &quot;samples&quot;</code></pre>
<p>As you can see in the previous code, epd.1 is an <code>epd.entity</code> object, with 10 different slots. The first five slots, contain some basic information: the entity number that was retrieved (<code>e_</code>), the post-bomb zone in which this entity is (<code>postbombzone</code>), the number of chronologies that are available for that entity in the EPD (<code>numberofchron</code>), whether the entity has datation information in Giesecke <em>et al.</em> <span class="citation">(2013)</span> (<code>isingiesecke</code>), and which one is the default chronology (<code>defaultchron</code>) to look for ages in the EPD. Then, the object has five slots (<code>entity</code>, <code>site</code>, <code>geochron</code>, <code>chron</code>, and <code>samples</code>) that store information from the previous <code>get_</code> functions. Hence, <code>epd.entity</code> objects store all available information from a particular entity in the EPD. This is the basic object in the package, and most methods works in the base of this object or the <code>epd.entity.df</code> object that expand it (we will see that later). Each one of the slots can be looked at using the symbol <code>@</code> or the <code>slot</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>e_</code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">slot</span>(epd.<span class="dv">1</span>, <span class="st">&quot;e_&quot;</span>)</code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>postbombzone</code></pre></div>
<pre><code>## [1] NH1
## Levels: NH1 NH2 NH3 SH12 SH3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>numberofchron</code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>isingiesecke</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>defaultchron</code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">slotNames</span>(epd.<span class="dv">1</span><span class="op">@</span>entity)</code></pre></div>
<pre><code>##  [1] &quot;entity&quot;    &quot;pentity&quot;   &quot;contact&quot;   &quot;coredrive&quot; &quot;descr&quot;    
##  [6] &quot;lithology&quot; &quot;loi&quot;       &quot;section&quot;   &quot;publent&quot;   &quot;publ&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">slotNames</span>(epd.<span class="dv">1</span><span class="op">@</span>site)</code></pre></div>
<pre><code>## [1] &quot;siteloc&quot;   &quot;sitedesc&quot;  &quot;siteinfo&quot;  &quot;country&quot;   &quot;region&quot;    &quot;region3rd&quot;
## [7] &quot;igcptype&quot;  &quot;infotype&quot;  &quot;publ&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">slotNames</span>(epd.<span class="dv">1</span><span class="op">@</span>geochron)</code></pre></div>
<pre><code>##  [1] &quot;geochron&quot; &quot;aar&quot;      &quot;c14&quot;      &quot;esr&quot;      &quot;ft&quot;       &quot;kar&quot;     
##  [7] &quot;pb210&quot;    &quot;si32&quot;     &quot;tl&quot;       &quot;useries&quot;  &quot;publ&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">slotNames</span>(epd.<span class="dv">1</span><span class="op">@</span>chron)</code></pre></div>
<pre><code>## [1] &quot;chron&quot;    &quot;agebound&quot; &quot;agebasis&quot; &quot;rational&quot; &quot;alsegs&quot;   &quot;panldpt&quot; 
## [7] &quot;synevent&quot; &quot;event&quot;    &quot;publ&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">slotNames</span>(epd.<span class="dv">1</span><span class="op">@</span>samples)</code></pre></div>
<pre><code>## [1] &quot;psamples&quot; &quot;analysts&quot; &quot;pagedpt&quot;  &quot;pcounts&quot;  &quot;pvars&quot;    &quot;syntype&quot; 
## [7] &quot;pvtrans&quot;  &quot;pgroup&quot;   &quot;groups&quot;</code></pre>
<p>Some of the relevant information can be also queried with specific functions from the <code>EPDr</code> package. In general, these functions use the name <code>check_</code> plus a descriptor of the information they check in the <code>epd.entity</code> object. For instance, <code>check_restriction</code> looks into the specific slots and tables that contains information on the use restrictions that apply to the data-set, and returns TRUE or FALSE depending on the case. However, <code>check_default_chron</code> returns also a logical (<code>TRUE</code> or <code>FALSE</code>) indicating whether the entity has a default chronology.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">check_restriction</span>(epd.<span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">check_default_chron</span>(epd.<span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
</div>
</div>
<div id="working-with-data-from-the-epd" class="section level1">
<h1><span class="header-section-number">6</span> Working with data from the EPD</h1>
<p>Once the user have find the data set he want to work with and have downloaded the data for that particular entity, there are several thinks he can do: Export data for (re-)calibration in CLAM or BACON, apply several transformations and standardization, and, finally, rearrange the data for further analysis or plotting.</p>
<div id="exporting-data-for-clam-or-bacon" class="section level2">
<h2><span class="header-section-number">6.1</span> Exporting data for CLAM or BACON</h2>
<p><code>EPDr</code> package provides several functions to reformat and export data to comply with format requirements from CLAM or BACON. These functions are named <code>export_</code> functions. There are five <code>export_</code> functions: <code>export_c14</code>, <code>export_agebasis</code>, <code>export_events</code>, <code>export_depths</code>, and <code>export_entity</code>.</p>
<p><code>export_c14</code> exports data from the C14 and GEOCHRON tables, which store information for samples and radiocarbon dates. <code>export_c14</code> requires a character string indicating the output format (“clam” or “bacon”), the C14 table (<code>x</code>) and the GEOCHRON table (<code>y</code>). Alternatively, it can be passed only a <code>epd.entity</code> object (<code>x</code> and <code>y</code> missing) and the function will look for both tables automatically on it.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">export_c14</span>(<span class="st">&quot;clam&quot;</span>, epd.<span class="dv">1</span><span class="op">@</span>geochron<span class="op">@</span>c14, epd.<span class="dv">1</span><span class="op">@</span>geochron<span class="op">@</span>geochron)</code></pre></div>
<pre><code>##     lab_ID C14_age cal_age error reservoir depth thickness
## 1 KIGI-350     910      NA    20        NA    83         5
## 2 KIGI-349    2420      NA   200        NA   118         5
## 3 KIGI-348    2900      NA   190        NA   140        10</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">export_c14</span>(<span class="st">&quot;bacon&quot;</span>, epd.<span class="dv">1</span><span class="op">@</span>geochron<span class="op">@</span>c14, epd.<span class="dv">1</span><span class="op">@</span>geochron<span class="op">@</span>geochron)</code></pre></div>
<pre><code>##      labID  age error depth
## 1 KIGI-350  910    20    83
## 2 KIGI-349 2420   200   118
## 3 KIGI-348 2900   190   140</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">export_c14</span>(<span class="st">&quot;clam&quot;</span>, epd.<span class="dv">1</span>)</code></pre></div>
<pre><code>##     lab_ID C14_age cal_age error reservoir depth thickness
## 1 KIGI-350     910      NA    20        NA    83         5
## 2 KIGI-349    2420      NA   200        NA   118         5
## 3 KIGI-348    2900      NA   190        NA   140        10</code></pre>
<p>Another function (<code>export_agebasis</code>) export the table AGEBASIS, which stores information on the data used to calibrate the different chronologies. <code>export_agebasis</code> takes also as arguments a character vector with output format, and an AGEBASIS table or an <code>epd.entity</code> object to look for it.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">export_agebasis</span>(<span class="st">&quot;clam&quot;</span>, epd.<span class="dv">1</span><span class="op">@</span>chron<span class="op">@</span>agebasis)</code></pre></div>
<pre><code>##         lab_ID C14_age cal_age error reservoir depth thickness
## 1    E1_CH1_S1       0      NA     1        NA     2        NA
##  [ reached getOption(&quot;max.print&quot;) -- omitted 8 rows ]</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">export_agebasis</span>(<span class="st">&quot;bacon&quot;</span>, epd.<span class="dv">1</span>)</code></pre></div>
<pre><code>##          labID  age error depth
## 1    E1_CH1_S1    0     1     2
## 2    E1_CH1_S2  910     1    83
##  [ reached getOption(&quot;max.print&quot;) -- omitted 7 rows ]</code></pre>
<p><code>export_events</code> function reformats and exports the data stored in the EVENTS and SYNEVENT tables, which refer to geological events registered in the entity (e.g., tephra, etc.). Similarly to <code>export_c14</code>, <code>export_events</code> requires two tables (SYNEVENT and EVENT) or the <code>epd.entity</code> objects in which to look for them.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">export_events</span>(<span class="st">&quot;clam&quot;</span>, epd.<span class="dv">1</span><span class="op">@</span>chron<span class="op">@</span>synevent, epd.<span class="dv">1</span><span class="op">@</span>chron<span class="op">@</span>event)</code></pre></div>
<pre><code>## [1] lab_ID    C14_age   cal_age   error     reservoir depth     thickness
## &lt;0 rows&gt; (or 0-length row.names)</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">export_events</span>(<span class="st">&quot;bacon&quot;</span>, epd.<span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] labID age   error depth
## &lt;0 rows&gt; (or 0-length row.names)</code></pre>
<p>Because, depths has the same output format in CLAM and BACON, <code>export_depths</code> do not require to specify the output format, and only needs a PSAMPLES or an <code>epd.entity</code> to look for that data of biological samples depth and export them.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">export_depths</span>(epd.<span class="dv">1</span><span class="op">@</span>samples<span class="op">@</span>psamples)</code></pre></div>
<pre><code>##  [1]  2  5  6  9 15 20 25 34 38 42
##  [ reached getOption(&quot;max.print&quot;) -- omitted 30 entries ]</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">export_depths</span>(epd.<span class="dv">1</span>)</code></pre></div>
<pre><code>##  [1]  2  5  6  9 15 20 25 34 38 42
##  [ reached getOption(&quot;max.print&quot;) -- omitted 30 entries ]</code></pre>
<p>Finally, <code>export_entity</code> function is a wrapping function that sequentially call all previous <code>export_</code> functions and combine the information to prepare a set of data ready for CLAM or BACON. Because, some data might be duplicated or may have conflicts between them (especially between AGEBASIS and C14), <code>export_entity</code> have several arguments to control how to resolve these conflicts. If that arguments are not called, the function runs interactively and request input from the user to resolve the conflicts on the way. <code>export_entity</code> requires the output format and an <code>epd.entity</code> object to look for all the necessary data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">export_entity</span>(<span class="st">&quot;clam&quot;</span>, epd.<span class="dv">1</span>)

##  Chronology has coincident data with C14 data and, hence, the later will be used
##  C14 data:
##  lab_ID  C14_age cal_age error   reserv. depth   thickn.
##  KIGI-350     910    NA   20 NA   83  5  
##  KIGI-349    2420    NA  200 NA  118  5  
##  KIGI-348    2900    NA  190 NA  140 10  
##  
##  Chronology data:
##  lab_ID  C14_age cal_age error   reserv. depth   thickn.
##  E1_CH1_S2    910    NA  1   NA   83 NA  
##  E1_CH1_S3   2420    NA  1   NA  118 NA  
##  E1_CH1_S4   2900    NA  1   NA  140 NA  
##  
##  Chronology has additional no-C14 data.
##  Chronology data:
##  lab_ID  C14_age cal_age error   reserv. depth   thickn.
##  E1_CH1_S1      0    NA  1   NA    2 NA  
##  E1_CH1_S5   4000    NA  1   NA  200 NA
##  
##  Incorporate these data to the chronology? (Yes: TRUE then Intro, No: FALSE then Intro)TRUE
##  
##        lab_ID C14_age cal_age error reservoir depth thickness
##  11 E1_CH1_S1       0      NA     1        NA     2        NA
##  1   KIGI-350     910      NA    20        NA    83         5
##  2   KIGI-349    2420      NA   200        NA   118         5
##  3   KIGI-348    2900      NA   190        NA   140        10
##  5  E1_CH1_S5    4000      NA     1        NA   200        NA</code></pre></div>
<p>The function, besides returning the data.frame with the right output format, write files in the working directory. It creates a different folder structure for CLAM or BACON files and then stores the files with the entity number (<code>e_</code>) and the appropriate extensions. If you are running the examples, just check your working directory (<code>getwd()</code>)</p>
</div>
<div id="standardizing-data" class="section level2">
<h2><span class="header-section-number">6.2</span> Standardizing data</h2>
<p>Because the data stored in the EPD are in the original format with minimal standardization, the user will need to run several manipulation and standardization steps depending on the goal of their analysis. <code>EPDr</code> package provides a set of functions to run some of these standardizations on the top of <code>epd.entity</code> objects.</p>
<div id="reformat-data-into-matrices-epd.entity.df" class="section level3">
<h3><span class="header-section-number">6.2.1</span> Reformat data into matrices (<code>epd.entity.df</code>)</h3>
<p>As already explained, <code>epd.entity</code> objects store a copy of the EPD tables for a specific entity. Hence, the data format are the same than in the PostgreSQL database, which is very convenient for database management and optimization, but not so much for data visualization and interpretation. The function <code>entity_to_matrices</code> transform several tables in the <code>epd.entity</code> objects and transform then into matrices that are more interpretable for normal use. For instance, ages are returned in the form of <code>samples</code>x<code>chronologies</code> matrix, while counts of biological particles are transformed into <code>samples</code>x<code>taxa</code> matrices. In order to keep a backup copy of the original data and another copy of the data in the matrices formats the function returns an object of the class <code>epd.entity.df</code>. This object inherit all properties (and data) of <code>epd.entity</code> objects and expand them with new slots: <code>@countstype</code>, <code>@countsprocessing</code>, <code>@taxatype</code>, <code>@taxaprocessing</code>, <code>@samplesdf</code>, <code>@agesdf</code>, <code>@commdf</code>, and <code>@nopodf</code>. In this way, the new object always have a backup copy of the original data and a copy of the transformed data in a more handy format.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">entity_to_matrices</span>(epd.<span class="dv">1</span>)
<span class="kw">slotNames</span>(epd.<span class="dv">1</span>)</code></pre></div>
<pre><code>##  [1] &quot;e_&quot;               &quot;postbombzone&quot;     &quot;numberofchron&quot;   
##  [4] &quot;isingiesecke&quot;     &quot;defaultchron&quot;     &quot;entity&quot;          
##  [7] &quot;site&quot;             &quot;geochron&quot;         &quot;chron&quot;           
## [10] &quot;samples&quot;          &quot;countstype&quot;       &quot;countsprocessing&quot;
## [13] &quot;taxatype&quot;         &quot;taxaprocessing&quot;   &quot;samplesdf&quot;       
## [16] &quot;agesdf&quot;           &quot;commdf&quot;           &quot;nopodf&quot;</code></pre>
<p>The four first slots trace information on data modification and standardizations from other functions (see later).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>countstype</code></pre></div>
<pre><code>## [1] Counts
## Levels: Counts Percentages</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>countsprocessing</code></pre></div>
<pre><code>## [1] Raw
## Levels: Raw Interpolated Ranged means</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>taxatype</code></pre></div>
<pre><code>## [1] Default
## Levels: Default Accepted Higher</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>taxaprocessing</code></pre></div>
<pre><code>## [1] Original
## Levels: Original Expanded</code></pre>
<p>The four last store the data in the matrix (or data.frame) format. <code>@samplesdf</code> has information on the biological samples id and labels.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">slotNames</span>(epd.<span class="dv">1</span><span class="op">@</span>samplesdf)</code></pre></div>
<pre><code>## [1] &quot;sample_&quot;     &quot;samplelabel&quot;</code></pre>
<p><code>@agesdf</code> stores information on the depth, ages and data quality of the samples.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">slotNames</span>(epd.<span class="dv">1</span><span class="op">@</span>agesdf)</code></pre></div>
<pre><code>## [1] &quot;depthcm&quot;     &quot;depthages&quot;   &quot;dataquality&quot;</code></pre>
<p><code>@commdf</code> stores taxa names, taxa ids, accepted taxa ids, higher taxa ids, taxa groups, and counts for each taxa.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">slotNames</span>(epd.<span class="dv">1</span><span class="op">@</span>commdf)</code></pre></div>
<pre><code>## [1] &quot;taxanames&quot;    &quot;taxa_&quot;        &quot;taxaaccepted&quot; &quot;taxamhvar&quot;   
## [5] &quot;taxagroupid&quot;  &quot;counts&quot;</code></pre>
<p>Finally <code>@nopodf</code> stores the same information than <code>@commdf</code> but for no-biological particles in the samples (e.g., added particles, total sums, etc.)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">slotNames</span>(epd.<span class="dv">1</span><span class="op">@</span>nopodf)</code></pre></div>
<pre><code>## [1] &quot;varnames&quot;    &quot;var_&quot;        &quot;varaccepted&quot; &quot;varmhvar&quot;    &quot;vargroupid&quot; 
## [6] &quot;counts&quot;</code></pre>
</div>
<div id="navigating-taxonomy-in-the-epd" class="section level3">
<h3><span class="header-section-number">6.2.2</span> Navigating taxonomy in the EPD</h3>
<p>Using the <code>get_taxonomy_epd</code> function the user can get a complete table for the taxonomy of the EPD. This table is useful for consulting but also it is fundamental for other functions to modify the taxonomy in certain tables of <code>epd.entity.df</code> objects.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.taxonomy &lt;-<span class="st"> </span><span class="kw">get_taxonomy_epd</span>(epd.connection)
epd.taxonomy</code></pre></div>
<pre><code>##      var_ accvar_ syntype   varcode
## 1       1       1    &lt;NA&gt;       Abi
## 2       2       1       N    Abi.ud
## 3       3       3    &lt;NA&gt;       Aca
## 4       4    1489    &lt;NA&gt;       Ace
## 5       5    1489       M  Ace.cf.c
##                                                 varname hvar_ mhvar_ auth_
## 1                                                 Abies    NA      1    NA
## 2                                         Abies undiff.    NA      1    NA
## 3                                                Acacia    NA      3    NA
## 4                                                  Acer    NA      4    NA
## 5                                 Acer cf. A. campestre    NA      4    NA
##                                                                     notes
## 1                                                                   B2004
## 2                                                                   B2004
## 3                                                                  FI1989
## 4                                                                    NEPF
## 5                                                                    NEPF
##      set_ groupid
## 1       1    TRSH
## 2       1    TRSH
## 3       1    TRSH
## 4       1    TRSH
## 5       1    TRSH
##  [ reached getOption(&quot;max.print&quot;) -- omitted 5475 rows ]</code></pre>
<p>In the previous table, for each of the variables in the EPD there are several information of interest to correct, modify, or standardize taxonomy of an entity. More importantly in the columns <code>accvar</code>, <code>mhvar</code>, and <code>groupid</code>. <code>accvar</code> indicates the <code>var_</code> number of the accepted taxa for that variable. This is relevant, because the data stored in the EPD are those reported by the original author. Hence, this column allows to unify the taxonomy across entities from different authors, regions and/or time periods, in which identification skills may have changed. The <code>taxa_to_acceptedtaxa</code> modify all information in the <code>@commdf</code> object to change taxa to the accepted taxa according to the <code>accvar</code> column in the taxonomy table.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>commdf<span class="op">@</span>taxanames</code></pre></div>
<pre><code>##  [1] &quot;Alnus&quot;                    &quot;Artemisia&quot;               
##  [3] &quot;Aster&quot;                    &quot;Betula&quot;                  
##  [5] &quot;Carpinus betulus&quot;         &quot;Caryophyllaceae&quot;         
##  [7] &quot;Castanea sativa&quot;          &quot;Cerealia-type&quot;           
##  [9] &quot;Chenopodiaceae&quot;           &quot;Corylus&quot;                 
## [11] &quot;Cyperaceae&quot;               &quot;Dipsacaceae&quot;             
## [13] &quot;Gramineae&quot;                &quot;Labiatae&quot;                
## [15] &quot;Leguminosae&quot;              &quot;Malvaceae&quot;               
## [17] &quot;Onagraceae&quot;               &quot;Pinus&quot;                   
## [19] &quot;Plantaginaceae&quot;           &quot;Plumbaginaceae&quot;          
## [21] &quot;Polygonaceae&quot;             &quot;Quercus&quot;                 
## [23] &quot;Ranunculaceae&quot;            &quot;Rhododendron&quot;            
## [25] &quot;Tilia&quot;                    &quot;Ulmus&quot;                   
## [27] &quot;Umbelliferae&quot;             &quot;Vaccinium&quot;               
## [29] &quot;Botrychium lunaria&quot;       &quot;Cryptogramma crispa&quot;     
## [31] &quot;Diphasium alpinum&quot;        &quot;Huperzia selago&quot;         
## [33] &quot;Polypodium vulgare&quot;       &quot;Selaginella selaginoides&quot;
## [35] &quot;Indeterminable: unknown&quot;  &quot;Compositae&quot;              
## [37] &quot;Carpinus orientalis&quot;      &quot;Geraniaceae&quot;             
## [39] &quot;Juglans regia&quot;            &quot;Polypodiaceae undiff.&quot;   
## [41] &quot;Cichorium&quot;                &quot;Pteridium undiff.&quot;       
## [43] &quot;Abies nordmanniana&quot;       &quot;Picea orientalis&quot;        
## [45] &quot;Pterocarya pterocarpa&quot;    &quot;Fagus orientalis&quot;        
## [47] &quot;Athyrium distentifolium&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">taxa_to_acceptedtaxa</span>(epd.<span class="dv">1</span>, epd.taxonomy)
epd.<span class="dv">1</span><span class="op">@</span>commdf<span class="op">@</span>taxanames</code></pre></div>
<pre><code>##  [1] &quot;Alnus&quot;                        &quot;Artemisia&quot;                   
##  [3] &quot;Aster-type&quot;                   &quot;Betula&quot;                      
##  [5] &quot;Carpinus betulus&quot;             &quot;Caryophyllaceae&quot;             
##  [7] &quot;Castanea&quot;                     &quot;Cerealia-type&quot;               
##  [9] &quot;Chenopodiaceae/Amaranthaceae&quot; &quot;Corylus&quot;                     
## [11] &quot;Cyperaceae&quot;                   &quot;Dipsacaceae&quot;                 
## [13] &quot;Gramineae&quot;                    &quot;Labiatae&quot;                    
## [15] &quot;Leguminosae&quot;                  &quot;Malvaceae&quot;                   
## [17] &quot;Onagraceae&quot;                   &quot;Pinus&quot;                       
## [19] &quot;Plantaginaceae&quot;               &quot;Plumbaginaceae&quot;              
## [21] &quot;Polygonaceae&quot;                 &quot;Quercus&quot;                     
## [23] &quot;Ranunculaceae&quot;                &quot;Rhododendron&quot;                
## [25] &quot;Tilia&quot;                        &quot;Ulmus&quot;                       
## [27] &quot;Umbelliferae&quot;                 &quot;Vaccinium&quot;                   
## [29] &quot;Botrychium lunaria-type&quot;      &quot;Cryptogramma crispa&quot;         
## [31] &quot;Lycopodium clavatum-type&quot;     &quot;Huperzia selago&quot;             
## [33] &quot;Polypodium&quot;                   &quot;Selaginella selaginoides&quot;    
## [35] &quot;Indeterminable: unknown&quot;      &quot;Compositae&quot;                  
## [37] &quot;Ostrya/Carpinus orientalis&quot;   &quot;Geraniaceae&quot;                 
## [39] &quot;Juglans&quot;                      &quot;Dryopteris-type&quot;             
## [41] &quot;Cichorium-type&quot;               &quot;Trilete spore(s)&quot;            
## [43] &quot;Abies&quot;                        &quot;Picea&quot;                       
## [45] &quot;Pterocarya fraxinifolia&quot;      &quot;Fagus&quot;                       
## [47] &quot;Woodsia-type&quot;</code></pre>
<blockquote>
<p>Check how the two <code>taxanames</code> lists have changed.</p>
</blockquote>
<p>Another column in the taxonomy table of the EPD (<code>mhvar</code>) has the <code>var_</code> numbers of the taxon higher taxonomical level, allowing to switch each variable to the higher taxonomical variable (or name).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>commdf<span class="op">@</span>taxanames</code></pre></div>
<pre><code>##  [1] &quot;Alnus&quot;                        &quot;Artemisia&quot;                   
##  [3] &quot;Aster-type&quot;                   &quot;Betula&quot;                      
##  [5] &quot;Carpinus betulus&quot;             &quot;Caryophyllaceae&quot;             
##  [7] &quot;Castanea&quot;                     &quot;Cerealia-type&quot;               
##  [9] &quot;Chenopodiaceae/Amaranthaceae&quot; &quot;Corylus&quot;                     
## [11] &quot;Cyperaceae&quot;                   &quot;Dipsacaceae&quot;                 
## [13] &quot;Gramineae&quot;                    &quot;Labiatae&quot;                    
## [15] &quot;Leguminosae&quot;                  &quot;Malvaceae&quot;                   
## [17] &quot;Onagraceae&quot;                   &quot;Pinus&quot;                       
## [19] &quot;Plantaginaceae&quot;               &quot;Plumbaginaceae&quot;              
## [21] &quot;Polygonaceae&quot;                 &quot;Quercus&quot;                     
## [23] &quot;Ranunculaceae&quot;                &quot;Rhododendron&quot;                
## [25] &quot;Tilia&quot;                        &quot;Ulmus&quot;                       
## [27] &quot;Umbelliferae&quot;                 &quot;Vaccinium&quot;                   
## [29] &quot;Botrychium lunaria-type&quot;      &quot;Cryptogramma crispa&quot;         
## [31] &quot;Lycopodium clavatum-type&quot;     &quot;Huperzia selago&quot;             
## [33] &quot;Polypodium&quot;                   &quot;Selaginella selaginoides&quot;    
## [35] &quot;Indeterminable: unknown&quot;      &quot;Compositae&quot;                  
## [37] &quot;Ostrya/Carpinus orientalis&quot;   &quot;Geraniaceae&quot;                 
## [39] &quot;Juglans&quot;                      &quot;Dryopteris-type&quot;             
## [41] &quot;Cichorium-type&quot;               &quot;Trilete spore(s)&quot;            
## [43] &quot;Abies&quot;                        &quot;Picea&quot;                       
## [45] &quot;Pterocarya fraxinifolia&quot;      &quot;Fagus&quot;                       
## [47] &quot;Woodsia-type&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="fl">1.</span>ht &lt;-<span class="st"> </span><span class="kw">taxa_to_highertaxa</span>(epd.<span class="dv">1</span>, epd.taxonomy)
epd.<span class="fl">1.</span>ht<span class="op">@</span>commdf<span class="op">@</span>taxanames</code></pre></div>
<pre><code>##  [1] &quot;Alnus&quot;                          &quot;Artemisia&quot;                     
##  [3] &quot;Asteroideae&quot;                    &quot;Betula&quot;                        
##  [5] &quot;Carpinus betulus&quot;               &quot;Caryophyllaceae&quot;               
##  [7] &quot;Castanea&quot;                       &quot;Cerealia-type&quot;                 
##  [9] &quot;Chenopodiaceae/Amaranthaceae&quot;   &quot;Corylus/Myrica&quot;                
## [11] &quot;Cyperaceae&quot;                     &quot;Dipsacaceae&quot;                   
## [13] &quot;Gramineae&quot;                      &quot;Labiatae&quot;                      
## [15] &quot;Leguminosae&quot;                    &quot;Malvaceae&quot;                     
## [17] &quot;Onagraceae&quot;                     &quot;Pinus&quot;                         
## [19] &quot;Plantaginaceae&quot;                 &quot;Plumbaginaceae&quot;                
## [21] &quot;Polygonaceae&quot;                   &quot;Quercus&quot;                       
## [23] &quot;Ranunculaceae&quot;                  &quot;Ericaceae-type&quot;                
## [25] &quot;Tilia&quot;                          &quot;Ulmus&quot;                         
## [27] &quot;Umbelliferae&quot;                   &quot;Botrychium&quot;                    
## [29] &quot;Cryptogramma crispa&quot;            &quot;Lycopodiaceae&quot;                 
## [31] &quot;Huperzia selago&quot;                &quot;Dryopteris-type&quot;               
## [33] &quot;Selaginella&quot;                    &quot;Indeterminable: unknown&quot;       
## [35] &quot;Compositae&quot;                     &quot;Ostrya/Carpinus orientalis&quot;    
## [37] &quot;Geraniaceae&quot;                    &quot;Juglans&quot;                       
## [39] &quot;Compositae subf. Cichorioideae&quot; &quot;Trilete spore(s)&quot;              
## [41] &quot;Abies&quot;                          &quot;Picea&quot;                         
## [43] &quot;Pterocarya fraxinifolia&quot;        &quot;Fagus&quot;</code></pre>
<blockquote>
<p>Check how ‘Castanea sativa’ have changed to ‘Castanea’.</p>
</blockquote>
<p>These two functions control for the fact that original data can include two or more variables (taxa) that after standardizing the taxonomy may belong to the same taxa. In this case the function sum the counts of the respective variables and modify the <code>@commdf@counts</code> in the object.</p>
<blockquote>
<p>Note in the previous example how the number of taxa have been reduced from 47 to 44.</p>
</blockquote>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rowSums</span>(epd.<span class="dv">1</span><span class="op">@</span>commdf<span class="op">@</span>counts)</code></pre></div>
<pre><code>##   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18 
## 205 179 319 354 246 222 356 239 366 332 239 286 293 292 347 402 347 310 
##  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36 
## 329 212 257 285 203 231 310 225 305 258 183 277 383 270 248 261 432 356 
##  37  38  39  40 
## 155 433 595 431</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rowSums</span>(epd.<span class="fl">1.</span>ht<span class="op">@</span>commdf<span class="op">@</span>counts)</code></pre></div>
<pre><code>##   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18 
## 205 179 319 354 246 222 356 239 366 332 239 286 293 292 347 402 347 310 
##  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36 
## 329 212 257 285 203 231 310 225 305 258 183 277 383 270 248 261 432 356 
##  37  38  39  40 
## 155 433 595 431</code></pre>
<p>This is the only way that EPD allow to upscale taxonomy. This implementation is however quite limited because it does not allow to standardize taxonomy at a specific taxonomic range (e.g., genus level). Further developments in the package may explore how to combine data from the entities with taxonomical databases, like those mined by packages like <code>taxize</code>.</p>
</div>
<div id="filtering-taxa" class="section level3">
<h3><span class="header-section-number">6.2.3</span> Filtering taxa</h3>
<p>Despite its name, entities in the EPD can contain data from different taxonomical groups, and not only for pollen or spores. Some entities can contain data for algae, acritarchs, etcetera (check <code>list_taxagroup</code> for the whole list). Hence, if one is interested in a particular biological group, he has to filter and remove the data from the rest of the groups. This is accomplished with the <code>filter_taxagroups</code> function. It takes two arguments. The first one must be an <code>epd.entity.df</code> object (or an <code>epd.entity</code> that is automatically transformed into an <code>epd.entity.df</code>) to be filtered. The second one is a character vector with the groups ids of interest to be retained. For instance, <code>DWAR</code> , <code>HERB</code>, <code>LIAN</code>, <code>TRSH</code>, <code>UPHE</code>, and <code>INUN</code> are all groups of pollen. So, if you want to work with upland plants pollen you can run the following code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">filter_taxagroups</span>(epd.<span class="dv">1</span>, <span class="kw">c</span>(<span class="st">&quot;DWAR&quot;</span>, <span class="st">&quot;HERB&quot;</span>, <span class="st">&quot;LIAN&quot;</span>, <span class="st">&quot;TRSH&quot;</span>, <span class="st">&quot;UPHE&quot;</span>, <span class="st">&quot;INUN&quot;</span>))
epd.<span class="dv">1</span><span class="op">@</span>commdf<span class="op">@</span>taxanames</code></pre></div>
<pre><code>##  [1] &quot;Alnus&quot;                        &quot;Artemisia&quot;                   
##  [3] &quot;Aster-type&quot;                   &quot;Betula&quot;                      
##  [5] &quot;Carpinus betulus&quot;             &quot;Caryophyllaceae&quot;             
##  [7] &quot;Castanea&quot;                     &quot;Cerealia-type&quot;               
##  [9] &quot;Chenopodiaceae/Amaranthaceae&quot; &quot;Corylus&quot;                     
## [11] &quot;Cyperaceae&quot;                   &quot;Dipsacaceae&quot;                 
## [13] &quot;Gramineae&quot;                    &quot;Labiatae&quot;                    
## [15] &quot;Leguminosae&quot;                  &quot;Malvaceae&quot;                   
## [17] &quot;Onagraceae&quot;                   &quot;Pinus&quot;                       
## [19] &quot;Plantaginaceae&quot;               &quot;Plumbaginaceae&quot;              
## [21] &quot;Polygonaceae&quot;                 &quot;Quercus&quot;                     
## [23] &quot;Ranunculaceae&quot;                &quot;Rhododendron&quot;                
## [25] &quot;Tilia&quot;                        &quot;Ulmus&quot;                       
## [27] &quot;Umbelliferae&quot;                 &quot;Vaccinium&quot;                   
## [29] &quot;Indeterminable: unknown&quot;      &quot;Compositae&quot;                  
## [31] &quot;Ostrya/Carpinus orientalis&quot;   &quot;Geraniaceae&quot;                 
## [33] &quot;Juglans&quot;                      &quot;Cichorium-type&quot;              
## [35] &quot;Abies&quot;                        &quot;Picea&quot;                       
## [37] &quot;Pterocarya fraxinifolia&quot;      &quot;Fagus&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rowSums</span>(epd.<span class="dv">1</span><span class="op">@</span>commdf<span class="op">@</span>counts)</code></pre></div>
<pre><code>##   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18 
## 136 112 194 256 155 116 196 175 275 213 146 216 132 176 236 271 212 227 
##  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36 
## 244 171 181 221 148 146 195 170 195 148 148 157 237 167 206 196 240 268 
##  37  38  39  40 
##  81 284 362 238</code></pre>
<blockquote>
<p>Note that we have filtered out Pteridophytes spores: “Botrychium”, “Cryptogramma crispa”, “Lycopodiaceae”, “Huperzia selago”, “Dryopteris-type”, “Selaginella”, “Trilete spore(s)”, “Pterocarya fraxinifolia”, “Fagus”.</p>
</blockquote>
<p>While the <code>filter_taxagroups</code> function use the groups defined in the EPD, the user may want to run a more personalized filtering. To do so, the <code>filter_taxa</code> allow filter taxa directly by their names. This function allows great versatility, but it also require great caution, because you need to specify the names exactly in the same way they are spelled in the EPD and thus in the <code>epd.entity.df</code> object.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="fl">1.</span>ft &lt;-<span class="st"> </span><span class="kw">filter_taxa</span>(epd.<span class="dv">1</span>, <span class="kw">c</span>(<span class="st">&quot;Alnus&quot;</span>, <span class="st">&quot;Artemisia&quot;</span>, <span class="st">&quot;Betula&quot;</span>, <span class="st">&quot;Carpinus betulus&quot;</span>, <span class="st">&quot;Corylus&quot;</span>), epd.taxonomy)
<span class="kw">head</span>(epd.<span class="fl">1.</span>ft<span class="op">@</span>commdf<span class="op">@</span>counts)</code></pre></div>
<pre><code>##   Alnus Artemisia Betula Carpinus betulus Corylus
## 1    32        15      0                0       4
## 2    35         5      0                0       1
## 3    47        10      0                0       2
## 4    45        19      0                1       2
## 5    24        15      0                0       0
## 6     9        21      0                0       1</code></pre>
<p>Caution has to be paid, because if you specify a taxon that is not in the <code>epd.entity.df</code> object, the function will create a new column with <code>NA</code> values. This is intentional, because when working with multiple entities you may still need to unify their taxonomy. However, if you misspell a name, the data will be withdrawn and a new column with a wrong name will be created.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="fl">1.</span>ft &lt;-<span class="st"> </span><span class="kw">filter_taxa</span>(epd.<span class="dv">1</span>, <span class="kw">c</span>(<span class="st">&quot;Aluns&quot;</span>, <span class="st">&quot;Artemisia&quot;</span>, <span class="st">&quot;Betula&quot;</span>, <span class="st">&quot;Carpinus betulus&quot;</span>, <span class="st">&quot;Carylus&quot;</span>), epd.taxonomy)
<span class="kw">head</span>(epd.<span class="fl">1.</span>ft<span class="op">@</span>commdf<span class="op">@</span>counts)</code></pre></div>
<pre><code>##   Aluns Artemisia Betula Carpinus betulus Carylus
## 1    NA        15      0                0      NA
## 2    NA         5      0                0      NA
## 3    NA        10      0                0      NA
## 4    NA        19      0                1      NA
## 5    NA        15      0                0      NA
## 6    NA        21      0                0      NA</code></pre>
<blockquote>
<p>Note how we misspelled “Alnus” and “Corylus” and the intended data were withdrawn and new columns with the misspelled names are created with <code>NA</code> values on them.</p>
</blockquote>
</div>
<div id="calculating-percentages" class="section level3">
<h3><span class="header-section-number">6.2.4</span> Calculating percentages</h3>
<p>Once, the data are reduced to those taxa of interest, the raw counts stored in the EPD can be transformed into percentages using the <code>counts_to_percentages</code> functions. This function only requires one argument with the <code>epd.entity.df</code> from which counts will be transformed into percentages relative to the complete sum of particles in each sample. It is thus important to previously properly filter the taxa to the taxa groups of interest to get meaningful percentages.</p>
<p>The function also modifies the slot <code>@countstype</code> to reflect that now the function has percentages and no raw counts.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>countstype</code></pre></div>
<pre><code>## [1] Counts
## Levels: Counts Percentages</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">counts_to_percentage</span>(epd.<span class="dv">1</span>)
epd.<span class="dv">1</span><span class="op">@</span>countstype</code></pre></div>
<pre><code>## [1] Percentages
## Levels: Counts Percentages</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(epd.<span class="dv">1</span><span class="op">@</span>commdf<span class="op">@</span>counts)</code></pre></div>
<pre><code>##       Alnus Artemisia Aster-type Betula Carpinus betulus Caryophyllaceae
## 1 23.529412 11.029412  0.7352941      0         0.000000       0.7352941
##   Castanea Cerealia-type Chenopodiaceae/Amaranthaceae   Corylus Cyperaceae
## 1 5.147059     1.4705882                            0 2.9411765  11.764706
##   Dipsacaceae Gramineae Labiatae Leguminosae Malvaceae Onagraceae Pinus
## 1           0 10.294118 0.000000           0  0.000000  0.0000000     0
##   Plantaginaceae Plumbaginaceae Polygonaceae Quercus Ranunculaceae
## 1      0.0000000      13.970588    15.441176       0      0.000000
##   Rhododendron     Tilia    Ulmus Umbelliferae Vaccinium
## 1    0.0000000 0.7352941 0.000000     0.000000         0
##   Indeterminable: unknown Compositae Ostrya/Carpinus orientalis
## 1                       0          0                          0
##   Geraniaceae  Juglans Cichorium-type Abies Picea Pterocarya fraxinifolia
## 1      0.0000 1.470588      0.7352941     0     0                       0
##   Fagus
## 1     0
##  [ reached getOption(&quot;max.print&quot;) -- omitted 5 rows ]</code></pre>
<p>Now, the sum of the counts for each sample should be 100 for all samples.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rowSums</span>(epd.<span class="dv">1</span><span class="op">@</span>commdf<span class="op">@</span>counts)</code></pre></div>
<pre><code>##   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18 
## 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 
##  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36 
## 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 
##  37  38  39  40 
## 100 100 100 100</code></pre>
</div>
<div id="using-updated-ages-from-giesecke-et-al.--giesecke_2013" class="section level3">
<h3><span class="header-section-number">6.2.5</span> Using updated ages from Giesecke <em>et al.</em> <span class="citation">(2013)</span></h3>
<p>In a publication from 2013, Giesecke <em>et al.</em> <span class="citation">(2013)</span> updated the chronologies (ages-depth models) for more than 800 entities in the database. Although the database itself was not updated with these new chronologies, they released all the information in four different tables in the <a href="https://doi.pangaea.de/10.1594/PANGAEA.804597">data repository Pagaea</a>, under <a href="https://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution 3.0 Unported</a>. The EPDr package provide a copy of these tables, and import the data from some of them into the <code>epd.entity</code> and <code>epd.entity.df</code> objects. When Giesecke <em>et al.</em> <span class="citation">(2013)</span> provide a chronology for an entity, the slot <code>@isingiesecke</code> is <code>TRUE</code>, and <code>FALSE</code> if they do not. However, the default chronology for each entity is recorded as in the original EPD. So, if you want to use ages estimated by Giesecke <em>et al.</em> <span class="citation">(2013)</span> you need to modified the slot <code>@defaultchron</code>. Most entities in the EPD have one or few chronologies, so <code>@defaultchron</code> is usually a number between <code>1</code> and <code>2(3)</code>, unless the entity has no chronologies at all and thus it is <code>0</code> or <code>NA</code>. To specify that other functions should use ages estimated by Giesecke <em>et al.</em> <span class="citation">(2013)</span> <code>@defaultchron</code> has to be <code>9999</code>.</p>
<p>We provide a function <code>giesecke_default_chron</code> that automatically check if the entity has updated ages in Giesecke <em>et al.</em> <span class="citation">(2013)</span> and, if so, update <code>@defaultchron</code> to <code>9999</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>defaultchron</code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>numberofchron</code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>isingiesecke</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">giesecke_default_chron</span>(epd.<span class="dv">1</span>)
epd.<span class="dv">1</span><span class="op">@</span>defaultchron</code></pre></div>
<pre><code>## [1] 9999</code></pre>
<blockquote>
<p>Note that <code>@numberofchron</code> reflect the total number of chronologies in the EPD without including those in Giesecke <em>et al.</em> <span class="citation">(2013)</span></p>
</blockquote>
</div>
<div id="interpolating-counts-data-to-specific-time-periods" class="section level3">
<h3><span class="header-section-number">6.2.6</span> Interpolating counts data to specific time periods</h3>
<p>Each EPD entity has counts data for samples at different depths, which combined with the different stratigraphy of each site (e.g., differential sedimentation rates among lakes), make that each counting data correspond to no particular and prestablished ages. Some times the user may need to estimate the counts data for a particular time period (and this can be important when comparing data from multiple entities and sites, but we will cover that later). The <code>interpolate_counts</code> function allow to interpolate counts in an <code>epd.entity.df</code> object (if an <code>epd.entity</code> object is provided this is previously transformed into an <code>edp.entity.df</code>) to those particular time periods specified by the user. The interpolation can be accomplished with three different methods: “linear”, “loess”, and “smooth spline”.</p>
<p>The function takes two mandatory arguments: <code>x</code> and <code>time</code>. <code>x</code> has to be an object of class <code>epd.entity.df</code> to be interpolated, and <code>time</code> has to be a numeric vector indicating the ages to which interpolate the counts. Other arguments are <code>chronology</code>, indicating the chronology that should be used to look for ages of the actual samples (if not provided the function use the default chronology according to the one specified in <code>x</code>), <code>method</code>, indicating the interpolation method to be used, <code>rep_negt</code> that should be <code>TRUE</code> or <code>FALSE</code>, indicating whether negative interpolated values should be replaced by <code>0</code>, and further arguments (e.g., <code>span</code>, <code>df</code>, and <code>...</code>) to control loess and smooth spline interpolation methods.</p>
<p>The function, in addition to calculate the</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="fl">1.</span>int &lt;-<span class="st"> </span><span class="kw">interpolate_counts</span>(epd.<span class="dv">1</span>, <span class="kw">c</span>(<span class="dv">1000</span>, <span class="dv">2000</span>, <span class="dv">3000</span>), <span class="dt">method =</span> <span class="st">&quot;linear&quot;</span>)</code></pre></div>
<p>The new <code>epd.entity.df</code> object returned by the function has been modified in several ways. In the first place the countings now reflect those estimated for the desired time periods.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>commdf<span class="op">@</span>counts[, <span class="dv">1</span><span class="op">:</span><span class="dv">5</span>]</code></pre></div>
<pre><code>##         Alnus Artemisia Aster-type Betula Carpinus betulus
## 1  23.5294118 11.029412  0.7352941      0        0.0000000
## 2  31.2500000  4.464286  0.0000000      0        0.0000000
## 3  24.2268041  5.154639  0.0000000      0        0.0000000
## 4  17.5781250  7.421875  0.0000000      0        0.3906250
## 5  15.4838710  9.677419  0.0000000      0        0.0000000
## 6   7.7586207 18.103448  0.8620690      0        0.0000000
## 7  16.3265306  9.183673  0.5102041      0        0.0000000
## 8  12.0000000  9.142857  0.0000000      0        0.0000000
## 9  12.0000000  6.181818  0.0000000      0        0.0000000
## 10 18.7793427  7.511737  0.4694836      0        0.0000000
##  [ reached getOption(&quot;max.print&quot;) -- omitted 30 rows ]</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="fl">1.</span>int<span class="op">@</span>commdf<span class="op">@</span>counts[, <span class="dv">1</span><span class="op">:</span><span class="dv">5</span>]</code></pre></div>
<pre><code>##       Alnus Artemisia Aster-type   Betula Carpinus betulus
## 1  5.186020  20.07165  1.0251259 0.000000        0.3293595
## 2 22.274364  24.32360  0.6716255 0.000000        0.0000000
## 3  3.625186  35.87556  1.3923787 0.451563        0.0000000</code></pre>
<p>Hence, the slot <code>@countsprocessing</code> is also modified to reflect the fact that data have been interpolated.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>countsprocessing</code></pre></div>
<pre><code>## [1] Raw
## Levels: Raw Interpolated Ranged means</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="fl">1.</span>int<span class="op">@</span>countsprocessing</code></pre></div>
<pre><code>## [1] Interpolated
## Levels: Samples Interpolated Ranged means</code></pre>
<p>Because the new ages are based in one of the chronologies, the function modifies also the tables with the ages (<code>@depthages</code>) and depths (<code>@depthcm</code>) to report the new ages (one column only with the chronology in which they were based) and estimated depths .</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>agesdf</code></pre></div>
<pre><code>## An object of class &quot;agesdf&quot;
## Slot &quot;depthcm&quot;:
##  [1]  2.0  5.0  6.0  9.0 15.0 20.0 25.0 34.0 38.0 42.0 46.0 50.0 53.5 56.5
## [15] 58.5 62.0 66.5 70.0
##  [ reached getOption(&quot;max.print&quot;) -- omitted 22 entries ]
## 
## Slot &quot;depthages&quot;:
##       1 giesecke
## 1     0   -45.70
## 2    34   -30.10
## 3    45   -24.88
## 4    79    -9.02
## 5   146    24.11
## 6   202    54.00
## 7   258    86.86
## 8   360   156.10
## 9   404   192.08
##  [ reached getOption(&quot;max.print&quot;) -- omitted 31 rows ]
## 
## Slot &quot;dataquality&quot;:
## data frame with 0 columns and 0 rows</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="fl">1.</span>int<span class="op">@</span>agesdf</code></pre></div>
<pre><code>## An object of class &quot;agesdf&quot;
## Slot &quot;depthcm&quot;:
## [1]  84.43726 114.53597 141.35469
## 
## Slot &quot;depthages&quot;:
##   giesecke
## 1     1000
## 2     2000
## 3     3000
## 
## Slot &quot;dataquality&quot;:
## data frame with 0 columns and 0 rows</code></pre>
<blockquote>
<p>Note that argument <code>chronology</code> was not specified and the default chronology (“giesecke”) was used here.</p>
</blockquote>
<p>Accordingly, the samples ids and labels are also modified.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="dv">1</span><span class="op">@</span>samplesdf</code></pre></div>
<pre><code>## An object of class &quot;samplesdf&quot;
## Slot &quot;sample_&quot;:
##  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20
##  [ reached getOption(&quot;max.print&quot;) -- omitted 20 entries ]
## 
## Slot &quot;samplelabel&quot;:
##  [1] &quot;1&quot;  &quot;2&quot;  &quot;3&quot;  &quot;4&quot;  &quot;5&quot;  &quot;6&quot;  &quot;7&quot;  &quot;8&quot;  &quot;9&quot;  &quot;10&quot; &quot;11&quot; &quot;12&quot; &quot;13&quot; &quot;14&quot;
## [15] &quot;15&quot; &quot;16&quot; &quot;17&quot; &quot;18&quot; &quot;19&quot; &quot;20&quot;
##  [ reached getOption(&quot;max.print&quot;) -- omitted 20 entries ]</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="fl">1.</span>int<span class="op">@</span>samplesdf</code></pre></div>
<pre><code>## An object of class &quot;samplesdf&quot;
## Slot &quot;sample_&quot;:
## [1] 10001 10002 10003
## 
## Slot &quot;samplelabel&quot;:
## [1] &quot;1000&quot; &quot;2000&quot; &quot;3000&quot;</code></pre>
<blockquote>
<p>Note that samples ids (<code>samples_</code>) start now from 10001 onwards, instead from 1 (which are reserved for original –not interpolated– data). This can be used as an extra warning flag.</p>
</blockquote>
</div>
<div id="average-counts-data-to-specific-time-ranges" class="section level3">
<h3><span class="header-section-number">6.2.7</span> Average counts data to specific time ranges</h3>
<p>Another approach to standardize counts through time is calculating average countings in particular time ranges (e.g., mean <em>Cedrus</em> pollen concentration between 1000 and 2000 cal BP). This can be carried out with the <code>intervals_counts</code> function. The function is quite similar to <code>interpolate_counts</code>, but it requires to arguments to specify time ranges (or intervals). The first one (<code>tmin</code>) is a numeric vector with starting values of the intervals and the second one (<code>tmax</code>) another numeric vector with the ending values of the intervals. It also requires an <code>epd.entity.df</code> object (as argument <code>x</code>), a chronology number (argument <code>chronology</code>), and accept a vector with labels for the new sample labels (argument <code>newlabels</code>). If <code>chronology</code> is not specified it use the default one for that entity, as specified in <code>x@defaultchron</code>. If <code>newlabels</code>is not specified the function creates new labels with the ranges definition.</p>
<p>Similarly to <code>interpolate_counts</code>, the new <code>epd.entity.df</code> object returned by the function is modified in several ways. In the first place the countings now reflect those estimated for the desired time ranges.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="fl">1.</span>ran &lt;-<span class="st"> </span><span class="kw">intervals_counts</span>(epd.<span class="dv">1</span>, <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1000</span>,<span class="dv">2000</span>,<span class="dv">3000</span>), <span class="kw">c</span>(<span class="dv">999</span>, <span class="dv">1999</span>, <span class="dv">2999</span>, <span class="dv">3999</span>))
epd.<span class="fl">1.</span>ran<span class="op">@</span>commdf<span class="op">@</span>counts[, <span class="dv">1</span><span class="op">:</span><span class="dv">5</span>]</code></pre></div>
<pre><code>##       Alnus Artemisia Aster-type Betula Carpinus betulus
## 1 10.562049  12.22890  0.4931589    0.0       0.09812701
## 2 14.292975  20.25722  0.5352651    0.0       0.09652510
## 3  8.923424  25.29436  0.6690736    0.0       0.25316456
## 4  4.135572  44.86940  0.0000000    2.5       0.00000000</code></pre>
<blockquote>
<p>Compare the values with those from percentages in the samples or as those interpolated for particular time periods.</p>
</blockquote>
<p>The slot <code>@countsprocessing</code> was also modified to reflect the fact that data have been averaged at time intervals.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="fl">1.</span>ran<span class="op">@</span>countsprocessing</code></pre></div>
<pre><code>## [1] Ranged means
## Levels: Samples Interpolated Ranged means</code></pre>
<p>Because the new ages are based in one of the chronologies, the function modifies also the tables with the ages (<code>@depthages</code>) and depths (<code>@depthcm</code>) to report the new ages (one column only with the chronology in which they were based) and estimated depths .</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="fl">1.</span>ran<span class="op">@</span>agesdf</code></pre></div>
<pre><code>## An object of class &quot;agesdf&quot;
## Slot &quot;depthcm&quot;:
## [1]  52.5000 101.4286 129.3000 155.2500
## 
## Slot &quot;depthages&quot;:
##    giesecke
## 1  419.7783
## 2 1543.0571
## 3 2548.9440
## 4 3520.9650
## 
## Slot &quot;dataquality&quot;:
## data frame with 0 columns and 0 rows</code></pre>
<blockquote>
<p>Note that argument <code>chronology</code> was not specified and the default chronology (“giesecke”) was used here. Also note that ages do not exactly match the intervals midpoint, they represent the average age of the samples used to calculate the average counts for each time range. Same thing happen with depth of the samples.</p>
</blockquote>
<p>Accordingly, the samples ids and labels are also modified.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epd.<span class="fl">1.</span>ran<span class="op">@</span>samplesdf</code></pre></div>
<pre><code>## An object of class &quot;samplesdf&quot;
## Slot &quot;sample_&quot;:
## [1] 20001 20002 20003 20004
## 
## Slot &quot;samplelabel&quot;:
## [1] &quot;0-999&quot;     &quot;1000-1999&quot; &quot;2000-2999&quot; &quot;3000-3999&quot;</code></pre>
<blockquote>
<p>Note that samples ids (<code>samples_</code>) start now from 20001 onwards, instead from 1 (which are reserved for original –not interpolated– data). This can be used as an extra warning flag. Note also the samples labels indicating the right ranges.</p>
</blockquote>
</div>
<div id="calculating-data-quality-using-blois_2011" class="section level3">
<h3><span class="header-section-number">6.2.8</span> Calculating data quality using <span class="citation">(Blois et al. 2011)</span></h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">blois_quality</span>(epd.<span class="dv">1</span>)

<span class="co"># Tabulate functions ----</span>
<span class="kw">table_by_taxa_age</span>(epd.<span class="dv">1</span>, <span class="kw">as.character</span>(<span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>)), <span class="st">&quot;Pinus&quot;</span>)

<span class="co"># Plotting functions ----</span>
<span class="kw">plot_diagram</span>(epd.<span class="dv">1</span>)


entity.list &lt;-<span class="st"> </span><span class="kw">list_e</span>(epd.connection, <span class="dt">country =</span> <span class="kw">c</span>(<span class="st">&quot;Spain&quot;</span>, <span class="st">&quot;Portugal&quot;</span>, <span class="st">&quot;France&quot;</span>, <span class="st">&quot;Switzerland&quot;</span>, <span class="st">&quot;Austria&quot;</span>, <span class="st">&quot;Italy&quot;</span>, <span class="st">&quot;Malta&quot;</span>, <span class="st">&quot;Algeria&quot;</span>, <span class="st">&quot;Tunisia&quot;</span>, <span class="st">&quot;Morocco&quot;</span>, <span class="st">&quot;Atlantic ocean&quot;</span>, <span class="st">&quot;Mediterranean Sea&quot;</span>))
entity.list &lt;-<span class="st"> </span><span class="kw">list_e</span>(epd.connection)<span class="op">$</span>e_
counts.all &lt;-<span class="st"> </span><span class="kw">lapply</span>(entity.list, get_entity, epd.connection)

counts.po &lt;-<span class="st"> </span><span class="kw">lapply</span>(counts.all, filter_taxagroups, <span class="kw">c</span>(<span class="st">&quot;HERB&quot;</span>, <span class="st">&quot;TRSH&quot;</span>, <span class="st">&quot;DWAR&quot;</span>, <span class="st">&quot;LIAN&quot;</span>, <span class="st">&quot;HEMI&quot;</span>, <span class="st">&quot;UPHE&quot;</span>))
counts.gi &lt;-<span class="st"> </span><span class="kw">lapply</span>(counts.po, giesecke_default_chron)
counts.un &lt;-<span class="st"> </span><span class="kw">remove_restricted</span>(counts.gi)
counts.wa &lt;-<span class="st"> </span><span class="kw">remove_wo_ages</span>(counts.un)

<span class="co"># Extract functions ----</span>
<span class="kw">extract_e</span>(epd.<span class="dv">1</span>)


percent.wa &lt;-<span class="st"> </span><span class="kw">lapply</span>(counts.wa, counts_to_percentage)
percent.int &lt;-<span class="st"> </span><span class="kw">lapply</span>(percent.wa, interpolate_counts, <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">22000</span>, <span class="dt">by =</span> <span class="dv">1000</span>))
percent.ran &lt;-<span class="st"> </span><span class="kw">lapply</span>(percent.wa, intervals_counts, <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">21000</span>, <span class="dt">by =</span> <span class="dv">1000</span>), <span class="kw">seq</span>(<span class="dv">999</span>, <span class="dv">21999</span>, <span class="dt">by =</span> <span class="dv">1000</span>))

epd.taxonomy &lt;-<span class="st"> </span><span class="kw">get_taxonomy_epd</span>(epd.connection)

counts.wa.acc &lt;-<span class="st"> </span><span class="kw">lapply</span>(counts.wa, taxa_to_acceptedtaxa, epd.taxonomy)
percent.wa.acc &lt;-<span class="st"> </span><span class="kw">lapply</span>(percent.wa, taxa_to_acceptedtaxa, epd.taxonomy)
percent.int.acc &lt;-<span class="st"> </span><span class="kw">lapply</span>(percent.int, taxa_to_acceptedtaxa, epd.taxonomy)

<span class="co"># counts.wa.hig &lt;- lapply(counts.wa, taxa_to_highertaxa, epd.taxonomy)</span>
<span class="co"># percent.wa.hig &lt;- lapply(percent.wa, taxa_to_highertaxa, epd.taxonomy)</span>
<span class="co"># percent.ran.hig &lt;- lapply(percent.ran, taxa_to_highertaxa, epd.taxonomy)</span>
<span class="co"># percent.int.hig &lt;- lapply(percent.int, taxa_to_highertaxa, epd.taxonomy)</span>

counts.wa.uni &lt;-<span class="st"> </span><span class="kw">unify_taxonomy</span>(counts.wa.acc, epd.taxonomy)
percent.wa.uni &lt;-<span class="st"> </span><span class="kw">unify_taxonomy</span>(percent.wa.acc, epd.taxonomy)
percent.int.uni &lt;-<span class="st"> </span><span class="kw">unify_taxonomy</span>(percent.int.acc, epd.taxonomy)




  
e &lt;-<span class="st"> </span><span class="kw">list_e</span>(epd.connection)<span class="op">$</span>e_
entity.list &lt;-<span class="st"> </span><span class="kw">lapply</span>(e[<span class="dv">1</span><span class="op">:</span><span class="dv">100</span>], get_entity, epd.connection)
<span class="kw">vapply</span>(entity.list, check_default_chron, <span class="dt">FUN.VALUE =</span> <span class="kw">logical</span>(<span class="dv">1</span>))
<span class="kw">vapply</span>(entity.list, check_restriction, <span class="dt">FUN.VALUE =</span> <span class="kw">logical</span>(<span class="dv">1</span>))

<span class="kw">remove_restricted</span>(entity.list)
<span class="kw">remove_wo_ages</span>(entity.list)

<span class="kw">lapply</span>(entity.list, extract_e)
<span class="kw">lapply</span>(entity.list, giesecke_default_chron)

<span class="kw">lapply</span>(entity.list, entity_to_matrices)

<span class="kw">lapply</span>(entity.list, filter_taxa_groups, <span class="kw">c</span>(<span class="st">&quot;DWAR&quot;</span>, <span class="st">&quot;HERB&quot;</span>, <span class="st">&quot;LIAN&quot;</span>, <span class="st">&quot;TRSH&quot;</span>, <span class="st">&quot;UPHE&quot;</span>, <span class="st">&quot;INUN&quot;</span>))

<span class="kw">lapply</span>(entity.list, filter_taxa, <span class="kw">c</span>(<span class="st">&quot;Pinus&quot;</span>,<span class="st">&quot;Quercus&quot;</span>,<span class="st">&quot;Urticaceae&quot;</span>), <span class="kw">get_taxonomy_epd</span>(epd.connection))
<span class="kw">lapply</span>(entity.list, taxa_to_acceptedtaxa, <span class="kw">get_taxonomy_epd</span>(epd.connection))
<span class="kw">lapply</span>(entity.list, taxa_to_highertaxa, <span class="kw">get_taxonomy_epd</span>(epd.connection))
<span class="kw">lapply</span>(entity.list, counts_to_percentages)
<span class="kw">lapply</span>(entity.list, interpolate_counts, <span class="kw">c</span>(<span class="dv">1000</span>, <span class="dv">2000</span>, <span class="dv">3000</span>))
<span class="kw">lapply</span>(entity.list, intervals_counts, <span class="kw">c</span>(<span class="dv">1000</span>, <span class="dv">2000</span>, <span class="dv">3000</span>), <span class="kw">c</span>(<span class="dv">2000</span>, <span class="dv">3000</span>, <span class="dv">4000</span>))
<span class="kw">unify_taxonomy</span>(entity.list, <span class="kw">get_taxonomy_epd</span>(epd.connection))
<span class="kw">lapply</span>(entity.list, table_by_taxa_age, <span class="kw">c</span>(<span class="st">&quot;Quercus&quot;</span>), <span class="kw">c</span>(<span class="st">&quot;1000&quot;</span>, <span class="st">&quot;2000&quot;</span>))
<span class="kw">map_taxa_age</span>(entity.list, <span class="st">&quot;Pinus&quot;</span>, <span class="st">&quot;1000&quot;</span>)
<span class="kw">lapply</span>(entity.list, blois_quality)



<span class="co"># Journals:</span>
<span class="co">#   Quartenary International</span>

Cedrus &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Cedrus&quot;</span>, <span class="st">&quot;Cedrus atlantica&quot;</span>, <span class="st">&quot;Cedrus cf. C. atlantica&quot;</span>, <span class="st">&quot;Cedrus-type&quot;</span>, <span class="st">&quot;cf. Cedrus&quot;</span>)

<span class="kw">mapTaxaAge</span>(percent.unr.ranges,  Cedrus, <span class="st">&quot;20000-22000&quot;</span>, <span class="dt">pres_abse =</span> T, <span class="dt">pollen_thres =</span> <span class="dv">0</span>)(percent.unr.ranges,  Cedrus, <span class="st">&quot;20000-22000&quot;</span>, <span class="dt">pres_abse =</span> T, <span class="dt">pollen_thres =</span> <span class="dv">0</span>)
<span class="kw">mapTaxaAge</span>(percent.unr.ranges, Cedrus, <span class="st">&quot;5500-6500&quot;</span>, <span class="dt">pres_abse =</span> F, <span class="dt">legend_range =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">5</span>))
<span class="kw">mapTaxaAge</span>(percent.unr.ranges,  Cedrus, <span class="st">&quot;20000-22000&quot;</span>, <span class="dt">pres_abse =</span> F, <span class="dt">legend_range =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">5</span>))

Pinus &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Pinus&quot;</span>, <span class="st">&quot;Pinus pinaster&quot;</span>, <span class="st">&quot;Pinus pinea&quot;</span>, <span class="st">&quot;Pinus sylvestris&quot;</span>, <span class="st">&quot;Pinus-type&quot;</span>, <span class="st">&quot;Pinus sp.&quot;</span>)
<span class="kw">mapTaxaAge</span>(percent.unr.ranges, Pinus, <span class="st">&quot;5500-6500&quot;</span>, <span class="dt">pres_abse =</span> T)
<span class="kw">mapTaxaAge</span>(percent.unr.ranges, Pinus, <span class="st">&quot;20000-22000&quot;</span>, <span class="dt">pres_abse =</span> T)
<span class="kw">mapTaxaAge</span>(percent.unr.ranges, Pinus, <span class="st">&quot;5500-6500&quot;</span>, <span class="dt">pres_abse =</span> F)
<span class="kw">mapTaxaAge</span>(percent.unr.ranges, Pinus, <span class="st">&quot;20000-22000&quot;</span>, <span class="dt">pres_abse =</span> F)


<span class="kw">mapTaxaAge</span>(percent.int.uni, <span class="st">&quot;Cedrus&quot;</span>, <span class="st">&quot;0&quot;</span>, <span class="dt">pres_abse =</span> F, <span class="dt">zoom_coords =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">20</span>, <span class="dv">180</span>, <span class="dv">30</span>, <span class="dv">80</span>), <span class="dt">points_pch =</span> <span class="dv">21</span>,
           <span class="dt">points_colour =</span> <span class="kw">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;red&quot;</span>), <span class="dt">points_fill =</span> <span class="kw">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;red&quot;</span>),
           <span class="dt">points_range_size =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="dt">map_title =</span> <span class="st">&quot;EPD sites&quot;</span>,
           <span class="dt">legend_range =</span> <span class="ot">NULL</span>, <span class="dt">legend_title =</span> <span class="ot">NULL</span>, <span class="dt">napoints_size =</span> <span class="dv">1</span>, <span class="dt">napoints_pch =</span> <span class="dv">21</span>, 
           <span class="dt">napoints_colour =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">napoints_fill =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">countries_fill_colour =</span> <span class="st">&quot;grey80&quot;</span>, <span class="dt">countries_border_colour =</span> <span class="st">&quot;grey90&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">disconnectFromEPD</span>(epd.connection)</code></pre></div>
</div>
</div>
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references">
<div id="ref-blois_2011">
<p>Blois, Jessica L., John W. (Jack) Williams, Eric C. Grimm, Stephen T. Jackson, and Russell W. Graham. 2011. “A Methodological Framework for Assessing and Reducing Temporal Uncertainty in Paleovegetation Mapping from Late-Quaternary Pollen Records.” <em>Quaternary Science Reviews</em> 30 (15): 1926–39. doi:<a href="https://doi.org/10.1016/j.quascirev.2011.04.017">10.1016/j.quascirev.2011.04.017</a>.</p>
</div>
<div id="ref-giesecke_2013">
<p>Giesecke, Thomas, Basil Davis, Simon Brewer, Walter Finsinger, Steffen Wolters, Maarten Blaauw, Jacques-Louis de Beaulieu, et al. 2013. “Towards Mapping the Late Quaternary Vegetation Change of Europe.” <em>Vegetation History and Archaeobotany</em> 23 (1): 75–86. doi:<a href="https://doi.org/10.1007/s00334-012-0390-y">10.1007/s00334-012-0390-y</a>.</p>
</div>
</div>
</div>



<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
